// Code generated by protoc-gen-go. DO NOT EDIT.
// source: command-line-arguments/all.proto

package types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Amount defines a transaction amount.
type Amount struct {
	// Cur is the currency of the amount.
	Cur string `protobuf:"bytes,1,opt,name=Cur,json=cur,proto3" json:"Cur,omitempty"`
	// Num is the value of the amount.
	Num                  string   `protobuf:"bytes,2,opt,name=Num,json=num,proto3" json:"Num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Amount) Reset()         { *m = Amount{} }
func (m *Amount) String() string { return proto.CompactTextString(m) }
func (*Amount) ProtoMessage()    {}
func (*Amount) Descriptor() ([]byte, []int) {
	return fileDescriptor_all_9532bbd8fa4a863e, []int{0}
}
func (m *Amount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Amount.Unmarshal(m, b)
}
func (m *Amount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Amount.Marshal(b, m, deterministic)
}
func (dst *Amount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Amount.Merge(dst, src)
}
func (m *Amount) XXX_Size() int {
	return xxx_messageInfo_Amount.Size(m)
}
func (m *Amount) XXX_DiscardUnknown() {
	xxx_messageInfo_Amount.DiscardUnknown(m)
}

var xxx_messageInfo_Amount proto.InternalMessageInfo

func (m *Amount) GetCur() string {
	if m != nil {
		return m.Cur
	}
	return ""
}

func (m *Amount) GetNum() string {
	if m != nil {
		return m.Num
	}
	return ""
}

func init() {
	proto.RegisterType((*Amount)(nil), "types.Amount")
}

func init() {
	proto.RegisterFile("command-line-arguments/all.proto", fileDescriptor_all_9532bbd8fa4a863e)
}

var fileDescriptor_all_9532bbd8fa4a863e = []byte{
	// 161 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x48, 0xce, 0xcf, 0xcd,
	0x4d, 0xcc, 0x4b, 0xd1, 0xcd, 0xc9, 0xcc, 0x4b, 0xd5, 0x4d, 0x2c, 0x4a, 0x2f, 0xcd, 0x4d, 0xcd,
	0x2b, 0x29, 0xd6, 0x4f, 0xcc, 0xc9, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2d, 0xa9,
	0x2c, 0x48, 0x2d, 0x56, 0xf2, 0xe1, 0x62, 0x73, 0xcc, 0xcd, 0x2f, 0xcd, 0x2b, 0x11, 0x92, 0xe1,
	0x62, 0x76, 0x2e, 0x2d, 0x92, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x74, 0xe2, 0xe2, 0x60, 0x90, 0x60,
	0xd0, 0x60, 0x30, 0x60, 0x08, 0x60, 0x08, 0x62, 0x4e, 0x2e, 0x2d, 0x02, 0xc9, 0xfa, 0x95, 0xe6,
	0x4a, 0x30, 0x61, 0xca, 0xe6, 0x95, 0xe6, 0x5a, 0xb1, 0x71, 0x30, 0x08, 0x30, 0x48, 0x30, 0x38,
	0x29, 0x78, 0x30, 0x06, 0x30, 0x44, 0x41, 0x8c, 0x6e, 0x60, 0x64, 0xe8, 0x60, 0x64, 0x98, 0xc0,
	0xc8, 0xb0, 0x83, 0x91, 0xe1, 0x06, 0x23, 0xc3, 0x0f, 0x46, 0x86, 0x0b, 0x4c, 0x0c, 0x49, 0x6c,
	0x60, 0xdb, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc2, 0xb9, 0x38, 0x60, 0xa1, 0x00, 0x00,
	0x00,
}
