// Code generated by protoc-gen-go. DO NOT EDIT.
// source: command-line-arguments/all.proto

package auth

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// GrantType defines the grant type when requesting a token.
type GrantType int32

const (
	GrantType__ GrantType = 0
	// GrantType_AuthorizationCode is the grant type used to exchange an authorization code with an access token.
	GrantType_AuthorizationCode GrantType = 1
	// GrantType_RefreshToken is the grant type used to refresh an access token.
	GrantType_RefreshToken GrantType = 2
)

var GrantType_name = map[int32]string{
	0: "_",
	1: "AuthorizationCode",
	2: "RefreshToken",
}
var GrantType_value = map[string]int32{
	"_":                 0,
	"AuthorizationCode": 1,
	"RefreshToken":      2,
}

func (x GrantType) String() string {
	return proto.EnumName(GrantType_name, int32(x))
}
func (GrantType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_all_8445971c0ff61d66, []int{0}
}

// GetAuthorizationCodeRequest is the request envelope to retrieve an authorization code.
type GetAuthorizationCodeRequest struct {
	// ClientID is your identifier provided during the registration process.
	ClientID string `protobuf:"bytes,1,opt,name=ClientID,json=client_id,proto3" json:"ClientID,omitempty"`
	// RedirectURI must match one of the URLs you have provided during the registration process.
	RedirectURI          string   `protobuf:"bytes,2,opt,name=RedirectURI,json=redirect_uri,proto3" json:"RedirectURI,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAuthorizationCodeRequest) Reset()         { *m = GetAuthorizationCodeRequest{} }
func (m *GetAuthorizationCodeRequest) String() string { return proto.CompactTextString(m) }
func (*GetAuthorizationCodeRequest) ProtoMessage()    {}
func (*GetAuthorizationCodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_all_8445971c0ff61d66, []int{0}
}
func (m *GetAuthorizationCodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAuthorizationCodeRequest.Unmarshal(m, b)
}
func (m *GetAuthorizationCodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAuthorizationCodeRequest.Marshal(b, m, deterministic)
}
func (dst *GetAuthorizationCodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAuthorizationCodeRequest.Merge(dst, src)
}
func (m *GetAuthorizationCodeRequest) XXX_Size() int {
	return xxx_messageInfo_GetAuthorizationCodeRequest.Size(m)
}
func (m *GetAuthorizationCodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAuthorizationCodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAuthorizationCodeRequest proto.InternalMessageInfo

func (m *GetAuthorizationCodeRequest) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

func (m *GetAuthorizationCodeRequest) GetRedirectURI() string {
	if m != nil {
		return m.RedirectURI
	}
	return ""
}

// Empty is an empty response.
type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_all_8445971c0ff61d66, []int{1}
}
func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (dst *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(dst, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

// CreateAccessTokenRequest is the request evelope to either exchange an authorization code with an access token or refresh a token.
type CreateAccessTokenRequest struct {
	// GrantType is an enum to defines which operation to perform.
	GrantType GrantType `protobuf:"varint,1,opt,name=GrantType,json=grant_type,proto3,enum=auth.GrantType" json:"GrantType,omitempty"`
	// Code is the authorization code previously received from the authorization server.
	Code string `protobuf:"bytes,2,opt,name=Code,json=code,proto3" json:"Code,omitempty"`
	// RedirectURI must match RedirectURI you have provided for the autorization code request.
	// Required only when GrantType is equal to "authorization_code".
	RedirectURI string `protobuf:"bytes,3,opt,name=RedirectURI,json=redirect_uri,proto3" json:"RedirectURI,omitempty"`
	// RefreshToken is the refresh token previously issued to the client.
	// Required only when GrantType is equal to "refresh_token"
	RefreshToken         string   `protobuf:"bytes,4,opt,name=RefreshToken,json=refresh_token,proto3" json:"RefreshToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccessTokenRequest) Reset()         { *m = CreateAccessTokenRequest{} }
func (m *CreateAccessTokenRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAccessTokenRequest) ProtoMessage()    {}
func (*CreateAccessTokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_all_8445971c0ff61d66, []int{2}
}
func (m *CreateAccessTokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccessTokenRequest.Unmarshal(m, b)
}
func (m *CreateAccessTokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccessTokenRequest.Marshal(b, m, deterministic)
}
func (dst *CreateAccessTokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccessTokenRequest.Merge(dst, src)
}
func (m *CreateAccessTokenRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAccessTokenRequest.Size(m)
}
func (m *CreateAccessTokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccessTokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccessTokenRequest proto.InternalMessageInfo

func (m *CreateAccessTokenRequest) GetGrantType() GrantType {
	if m != nil {
		return m.GrantType
	}
	return GrantType__
}

func (m *CreateAccessTokenRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *CreateAccessTokenRequest) GetRedirectURI() string {
	if m != nil {
		return m.RedirectURI
	}
	return ""
}

func (m *CreateAccessTokenRequest) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

// CreateAccessTokenResponse is the response envelope containing the access token.
type CreateAccessTokenResponse struct {
	// AccessToken issued by the authorization server.
	AccessToken string `protobuf:"bytes,1,opt,name=AccessToken,json=access_token,proto3" json:"AccessToken,omitempty"`
	// TokenType is the type of the token, always "bearer".
	TokenType string `protobuf:"bytes,2,opt,name=TokenType,json=token_type,proto3" json:"TokenType,omitempty"`
	// ExpiresIn is the duration in seconds that the access token remains valid.
	ExpiresIn int32 `protobuf:"varint,3,opt,name=ExpiresIn,json=expires_in,proto3" json:"ExpiresIn,omitempty"`
	// RefreshToken is the token to renew an expired access token.
	RefreshToken         string   `protobuf:"bytes,4,opt,name=RefreshToken,json=refresh_token,proto3" json:"RefreshToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccessTokenResponse) Reset()         { *m = CreateAccessTokenResponse{} }
func (m *CreateAccessTokenResponse) String() string { return proto.CompactTextString(m) }
func (*CreateAccessTokenResponse) ProtoMessage()    {}
func (*CreateAccessTokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_all_8445971c0ff61d66, []int{3}
}
func (m *CreateAccessTokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccessTokenResponse.Unmarshal(m, b)
}
func (m *CreateAccessTokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccessTokenResponse.Marshal(b, m, deterministic)
}
func (dst *CreateAccessTokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccessTokenResponse.Merge(dst, src)
}
func (m *CreateAccessTokenResponse) XXX_Size() int {
	return xxx_messageInfo_CreateAccessTokenResponse.Size(m)
}
func (m *CreateAccessTokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccessTokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccessTokenResponse proto.InternalMessageInfo

func (m *CreateAccessTokenResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *CreateAccessTokenResponse) GetTokenType() string {
	if m != nil {
		return m.TokenType
	}
	return ""
}

func (m *CreateAccessTokenResponse) GetExpiresIn() int32 {
	if m != nil {
		return m.ExpiresIn
	}
	return 0
}

func (m *CreateAccessTokenResponse) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func init() {
	proto.RegisterType((*GetAuthorizationCodeRequest)(nil), "auth.GetAuthorizationCodeRequest")
	proto.RegisterType((*Empty)(nil), "auth.Empty")
	proto.RegisterType((*CreateAccessTokenRequest)(nil), "auth.CreateAccessTokenRequest")
	proto.RegisterType((*CreateAccessTokenResponse)(nil), "auth.CreateAccessTokenResponse")
	proto.RegisterEnum("auth.GrantType", GrantType_name, GrantType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthorizationServiceClient is the client API for AuthorizationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthorizationServiceClient interface {
	// GetAuthorizationCode creates an authorization code.
	GetAuthorizationCode(ctx context.Context, in *GetAuthorizationCodeRequest, opts ...grpc.CallOption) (*Empty, error)
	// CreateAccessToken exchanges an authorization code with an access token.
	CreateAccessToken(ctx context.Context, in *CreateAccessTokenRequest, opts ...grpc.CallOption) (*CreateAccessTokenResponse, error)
}

type authorizationServiceClient struct {
	cc *grpc.ClientConn
}

func NewAuthorizationServiceClient(cc *grpc.ClientConn) AuthorizationServiceClient {
	return &authorizationServiceClient{cc}
}

func (c *authorizationServiceClient) GetAuthorizationCode(ctx context.Context, in *GetAuthorizationCodeRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/auth.AuthorizationService/GetAuthorizationCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizationServiceClient) CreateAccessToken(ctx context.Context, in *CreateAccessTokenRequest, opts ...grpc.CallOption) (*CreateAccessTokenResponse, error) {
	out := new(CreateAccessTokenResponse)
	err := c.cc.Invoke(ctx, "/auth.AuthorizationService/CreateAccessToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthorizationServiceServer is the server API for AuthorizationService service.
type AuthorizationServiceServer interface {
	// GetAuthorizationCode creates an authorization code.
	GetAuthorizationCode(context.Context, *GetAuthorizationCodeRequest) (*Empty, error)
	// CreateAccessToken exchanges an authorization code with an access token.
	CreateAccessToken(context.Context, *CreateAccessTokenRequest) (*CreateAccessTokenResponse, error)
}

func RegisterAuthorizationServiceServer(s *grpc.Server, srv AuthorizationServiceServer) {
	s.RegisterService(&_AuthorizationService_serviceDesc, srv)
}

func _AuthorizationService_GetAuthorizationCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuthorizationCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizationServiceServer).GetAuthorizationCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthorizationService/GetAuthorizationCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizationServiceServer).GetAuthorizationCode(ctx, req.(*GetAuthorizationCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthorizationService_CreateAccessToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccessTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizationServiceServer).CreateAccessToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.AuthorizationService/CreateAccessToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizationServiceServer).CreateAccessToken(ctx, req.(*CreateAccessTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthorizationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "auth.AuthorizationService",
	HandlerType: (*AuthorizationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAuthorizationCode",
			Handler:    _AuthorizationService_GetAuthorizationCode_Handler,
		},
		{
			MethodName: "CreateAccessToken",
			Handler:    _AuthorizationService_CreateAccessToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "command-line-arguments/all.proto",
}

func init() {
	proto.RegisterFile("command-line-arguments/all.proto", fileDescriptor_all_8445971c0ff61d66)
}

var fileDescriptor_all_8445971c0ff61d66 = []byte{
	// 652 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xbf, 0x53, 0x13, 0x41,
	0x14, 0xde, 0x3d, 0x02, 0x93, 0x2c, 0xbf, 0xc2, 0x0e, 0x45, 0x38, 0x1d, 0x58, 0xd3, 0x08, 0x8c,
	0x49, 0x04, 0x3b, 0xba, 0x80, 0x88, 0x8c, 0x0d, 0x13, 0x63, 0x63, 0x93, 0x59, 0x2f, 0xcf, 0xbb,
	0x1d, 0x93, 0xdd, 0x73, 0x77, 0x0f, 0x88, 0xa3, 0x33, 0x8e, 0x36, 0x94, 0x0c, 0x76, 0x76, 0xfe,
	0x17, 0x76, 0xb6, 0x96, 0xce, 0xd8, 0x68, 0x63, 0xe5, 0x1f, 0x61, 0xe9, 0xdc, 0x1e, 0x20, 0xe1,
	0x02, 0x85, 0xd5, 0xcd, 0xbc, 0xef, 0x7b, 0xbb, 0xef, 0xfb, 0xde, 0x77, 0x4b, 0x58, 0xa0, 0xfa,
	0x7d, 0x2e, 0xbb, 0xb5, 0x9e, 0x90, 0x50, 0xe3, 0x3a, 0x4c, 0xfa, 0x20, 0xad, 0x69, 0xf0, 0x5e,
	0xaf, 0x1e, 0x6b, 0x65, 0x15, 0x2d, 0xf0, 0xc4, 0x46, 0xfe, 0xcd, 0x50, 0xa9, 0xb0, 0x07, 0x0d,
	0x1e, 0x8b, 0x06, 0x97, 0x52, 0x59, 0x6e, 0x85, 0x92, 0x26, 0xe3, 0xf8, 0x77, 0xdc, 0x27, 0xa8,
	0x85, 0x20, 0x6b, 0xe6, 0x80, 0x87, 0x21, 0xe8, 0x86, 0x8a, 0x1d, 0x23, 0xcf, 0xae, 0xbe, 0x21,
	0x37, 0x76, 0xc0, 0x36, 0x13, 0x1b, 0x29, 0x2d, 0x5e, 0x39, 0x68, 0x4b, 0x75, 0xa1, 0x05, 0x2f,
	0x13, 0x30, 0x96, 0xde, 0x26, 0xc5, 0xad, 0x9e, 0x00, 0x69, 0x77, 0xef, 0x57, 0x30, 0xc3, 0xcb,
	0xa5, 0x4d, 0x52, 0x44, 0x15, 0xb4, 0x8c, 0xee, 0xa2, 0x3d, 0xd4, 0x2a, 0x05, 0x0e, 0xeb, 0x88,
	0x2e, 0xad, 0x91, 0xc9, 0x16, 0x74, 0x85, 0x86, 0xc0, 0x3e, 0x69, 0xed, 0x56, 0xbc, 0x1c, 0x77,
	0x4a, 0x9f, 0xc2, 0x9d, 0x44, 0x8b, 0x8d, 0x89, 0x22, 0x2a, 0xa3, 0x0a, 0xaa, 0xce, 0x92, 0xf1,
	0xed, 0x7e, 0x6c, 0x07, 0xe7, 0x85, 0x5f, 0x98, 0x54, 0xb6, 0x34, 0x70, 0x0b, 0xcd, 0x20, 0x00,
	0x63, 0xda, 0xea, 0x05, 0xc8, 0xb3, 0x69, 0x36, 0x48, 0x69, 0x47, 0x73, 0x69, 0xdb, 0x83, 0x18,
	0xdc, 0x38, 0x33, 0xeb, 0xb3, 0xf5, 0xd4, 0x92, 0xfa, 0x79, 0x79, 0xe8, 0x4e, 0x12, 0xa6, 0xe5,
	0x8e, 0x1d, 0xc4, 0x40, 0x17, 0x49, 0x21, 0x15, 0x36, 0x62, 0xb2, 0x42, 0xa0, 0xba, 0x70, 0x59,
	0xc0, 0xd8, 0xf5, 0x02, 0x68, 0x83, 0x4c, 0xb5, 0xe0, 0xb9, 0x06, 0x13, 0xb9, 0x09, 0x2b, 0x85,
	0x1c, 0x7f, 0x5a, 0x67, 0x78, 0xc7, 0xa6, 0x84, 0x73, 0x81, 0x3f, 0x31, 0x59, 0x18, 0x21, 0xd0,
	0xc4, 0x4a, 0x1a, 0x37, 0xc5, 0x85, 0xf2, 0x08, 0xcb, 0xa7, 0xb8, 0x83, 0xb3, 0x43, 0xe9, 0x0a,
	0x29, 0x39, 0xa2, 0x33, 0x24, 0xaf, 0x8c, 0x38, 0x56, 0xa6, 0x7f, 0x85, 0x94, 0xb6, 0x0f, 0x63,
	0xa1, 0xc1, 0xec, 0x4a, 0xa7, 0x6e, 0x7c, 0x98, 0x0a, 0x19, 0xd8, 0x11, 0xf2, 0xbf, 0xb5, 0xad,
	0x3e, 0xba, 0xb0, 0x1f, 0x5a, 0x22, 0xb8, 0x53, 0x46, 0xbe, 0x57, 0x44, 0x74, 0x81, 0xcc, 0xe5,
	0x12, 0x56, 0xc6, 0x0e, 0x9a, 0x1f, 0xbe, 0xab, 0xec, 0xa5, 0x55, 0xdf, 0xab, 0xa0, 0xf5, 0xf7,
	0x05, 0x32, 0x3f, 0xd4, 0xf5, 0x18, 0xf4, 0xbe, 0x08, 0x80, 0x7e, 0xc5, 0x64, 0x7e, 0x54, 0x66,
	0xe9, 0xad, 0xd3, 0x2c, 0x5c, 0x9d, 0x67, 0x7f, 0x32, 0xa3, 0xb8, 0xcc, 0x55, 0x5f, 0x9f, 0x34,
	0x03, 0x32, 0x3d, 0xc4, 0xa5, 0x4b, 0x2d, 0xb0, 0x5a, 0xc0, 0x3e, 0x30, 0x2e, 0x19, 0xbf, 0x08,
	0xb1, 0x34, 0x26, 0x75, 0x7f, 0xed, 0x81, 0xd0, 0xc6, 0xb2, 0x81, 0x4a, 0x98, 0x04, 0xe8, 0x32,
	0xab, 0x98, 0xbe, 0xbe, 0xe5, 0xdd, 0xf7, 0xdf, 0x1f, 0x3c, 0x42, 0x8b, 0x8d, 0xfd, 0xb5, 0x46,
	0x0a, 0x1f, 0x79, 0xe8, 0xd8, 0x73, 0x4e, 0xd2, 0x8f, 0x1e, 0x99, 0xcb, 0x85, 0x81, 0x2e, 0x66,
	0x43, 0x5e, 0xf5, 0x1b, 0xf8, 0x4b, 0x57, 0xe2, 0x59, 0x8a, 0xaa, 0x5f, 0xf0, 0x49, 0xf3, 0x13,
	0xbe, 0x2c, 0x6d, 0x61, 0x48, 0x9a, 0x6b, 0x63, 0x6e, 0x7f, 0x75, 0x3f, 0x69, 0x47, 0x20, 0x9d,
	0xa6, 0x80, 0x4b, 0x06, 0x87, 0x41, 0xc4, 0x65, 0x08, 0xcc, 0x46, 0x30, 0x42, 0x10, 0x3b, 0x10,
	0x36, 0xca, 0x9d, 0xc1, 0xda, 0x91, 0x30, 0x0c, 0x64, 0x37, 0x56, 0x42, 0x5a, 0x26, 0x0c, 0xe3,
	0x3d, 0xa3, 0x58, 0x62, 0xce, 0x3c, 0x72, 0x4b, 0x4e, 0xef, 0xd0, 0x59, 0x87, 0xc9, 0x8c, 0x99,
	0xd9, 0xc0, 0xab, 0xd5, 0x52, 0xea, 0x8d, 0xab, 0xfe, 0x33, 0xc7, 0x1f, 0x3b, 0xf2, 0xd0, 0xe6,
	0xd2, 0x43, 0xbc, 0x87, 0x9e, 0xba, 0x77, 0xef, 0x2d, 0x46, 0x47, 0x18, 0x1d, 0x63, 0xf4, 0x19,
	0xa3, 0x1f, 0x18, 0xfd, 0xc1, 0xe8, 0x9b, 0x87, 0x9e, 0x4d, 0xb8, 0x77, 0xec, 0xde, 0xdf, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xe0, 0xfc, 0x05, 0xab, 0x3d, 0x05, 0x00, 0x00,
}
