// Code generated by protoc-gen-go. DO NOT EDIT.
// source: command-line-arguments/all.proto

package accounts

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"
import _ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
import types "github.com/openbank/gunk/gunk/v1/types"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// EntityType describes the type of the entity.
type EntityType int32

const (
	EntityType__ EntityType = 0
	// EntityType_Pers is an individual customer.
	EntityType_Pers EntityType = 1
	// EntityType_Org is an organisation customer.
	EntityType_Org EntityType = 2
)

var EntityType_name = map[int32]string{
	0: "_",
	1: "Pers",
	2: "Org",
}
var EntityType_value = map[string]int32{
	"_":    0,
	"Pers": 1,
	"Org":  2,
}

func (x EntityType) String() string {
	return proto.EnumName(EntityType_name, int32(x))
}
func (EntityType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_all_f3d029296c464da3, []int{0}
}

// Account holds all details about a bank account.
type Account struct {
	// AccountID is the unique identifier of an account.
	AccountID string `protobuf:"bytes,1,opt,name=AccountID,json=account_id,proto3" json:"AccountID,omitempty"`
	// TODO: add comment.
	Branch string `protobuf:"bytes,2,opt,name=Branch,json=branch,proto3" json:"Branch,omitempty"`
	// TODO: add comment.
	BranchName string `protobuf:"bytes,3,opt,name=BranchName,json=branch_name,proto3" json:"BranchName,omitempty"`
	// Status is the status of the account.
	Status string `protobuf:"bytes,4,opt,name=Status,json=status,proto3" json:"Status,omitempty"`
	// TODO: add comment.
	AccruedInterestAtMaturityDate string `protobuf:"bytes,5,opt,name=AccruedInterestAtMaturityDate,json=accrued_interest_at_maturity_date,proto3" json:"AccruedInterestAtMaturityDate,omitempty"`
	// TODO: add comment.
	AmountDue *types.Amount `protobuf:"bytes,6,opt,name=AmountDue,json=amount_due,proto3" json:"AmountDue,omitempty"`
	// TODO: add comment.
	AvailableBalance *types.Amount `protobuf:"bytes,7,opt,name=AvailableBalance,json=available_balance,proto3" json:"AvailableBalance,omitempty"`
	// TODO: add comment.
	AvailableCreditLimit string `protobuf:"bytes,8,opt,name=AvailableCreditLimit,json=available_credit_limit,proto3" json:"AvailableCreditLimit,omitempty"`
	// TODO: add comment.
	CheckingInterestRate string `protobuf:"bytes,9,opt,name=CheckingInterestRate,json=checking_interest_rate,proto3" json:"CheckingInterestRate,omitempty"`
	// ContractDate is the date of the contract initialization.
	ContractDate string `protobuf:"bytes,10,opt,name=ContractDate,json=contract_date,proto3" json:"ContractDate,omitempty"`
	// CreditLimit is the allowed credit limit.
	CreditLimit string `protobuf:"bytes,11,opt,name=CreditLimit,json=credit_limit,proto3" json:"CreditLimit,omitempty"`
	// TODO: add comment.
	CurrentAccruedInterest string `protobuf:"bytes,12,opt,name=CurrentAccruedInterest,json=current_accrued_interest,proto3" json:"CurrentAccruedInterest,omitempty"`
	// TODO: add comment.
	CurrentBalance *types.Amount `protobuf:"bytes,13,opt,name=CurrentBalance,json=current_balance,proto3" json:"CurrentBalance,omitempty"`
	// CurrentTerm is the account validity period.
	CurrentTerm string `protobuf:"bytes,14,opt,name=CurrentTerm,json=current_term,proto3" json:"CurrentTerm,omitempty"`
	// DueDate is the loan maturity date.
	DueDate string `protobuf:"bytes,15,opt,name=DueDate,json=due_date,proto3" json:"DueDate,omitempty"`
	// TODO: add comment.
	InterestRate string `protobuf:"bytes,16,opt,name=InterestRate,json=interest_rate,proto3" json:"InterestRate,omitempty"`
	// MajorType is the account type.
	MajorType types.MajorType `protobuf:"varint,17,opt,name=MajorType,json=major_type,proto3,enum=types.MajorType" json:"MajorType,omitempty"`
	// MajorCategory is the account category.
	MajorCategory types.MajorCategory `protobuf:"varint,18,opt,name=MajorCategory,json=major_category,proto3,enum=types.MajorCategory" json:"MajorCategory,omitempty"`
	// MaturityDate is the maturity date, format is ISO 8601
	MaturityDate string `protobuf:"bytes,19,opt,name=MaturityDate,json=maturity_date,proto3" json:"MaturityDate,omitempty"`
	// TODO: add comment.
	NextPaymentDueDate string `protobuf:"bytes,20,opt,name=NextPaymentDueDate,json=next_payment_due_date,proto3" json:"NextPaymentDueDate,omitempty"`
	// OwnerName is the name of the account's owner.
	OwnerName string `protobuf:"bytes,21,opt,name=OwnerName,json=owner_name,proto3" json:"OwnerName,omitempty"`
	// TODO: add comment.
	StartDate            string   `protobuf:"bytes,22,opt,name=StartDate,json=start_date,proto3" json:"StartDate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_all_f3d029296c464da3, []int{0}
}
func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (dst *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(dst, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetAccountID() string {
	if m != nil {
		return m.AccountID
	}
	return ""
}

func (m *Account) GetBranch() string {
	if m != nil {
		return m.Branch
	}
	return ""
}

func (m *Account) GetBranchName() string {
	if m != nil {
		return m.BranchName
	}
	return ""
}

func (m *Account) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Account) GetAccruedInterestAtMaturityDate() string {
	if m != nil {
		return m.AccruedInterestAtMaturityDate
	}
	return ""
}

func (m *Account) GetAmountDue() *types.Amount {
	if m != nil {
		return m.AmountDue
	}
	return nil
}

func (m *Account) GetAvailableBalance() *types.Amount {
	if m != nil {
		return m.AvailableBalance
	}
	return nil
}

func (m *Account) GetAvailableCreditLimit() string {
	if m != nil {
		return m.AvailableCreditLimit
	}
	return ""
}

func (m *Account) GetCheckingInterestRate() string {
	if m != nil {
		return m.CheckingInterestRate
	}
	return ""
}

func (m *Account) GetContractDate() string {
	if m != nil {
		return m.ContractDate
	}
	return ""
}

func (m *Account) GetCreditLimit() string {
	if m != nil {
		return m.CreditLimit
	}
	return ""
}

func (m *Account) GetCurrentAccruedInterest() string {
	if m != nil {
		return m.CurrentAccruedInterest
	}
	return ""
}

func (m *Account) GetCurrentBalance() *types.Amount {
	if m != nil {
		return m.CurrentBalance
	}
	return nil
}

func (m *Account) GetCurrentTerm() string {
	if m != nil {
		return m.CurrentTerm
	}
	return ""
}

func (m *Account) GetDueDate() string {
	if m != nil {
		return m.DueDate
	}
	return ""
}

func (m *Account) GetInterestRate() string {
	if m != nil {
		return m.InterestRate
	}
	return ""
}

func (m *Account) GetMajorType() types.MajorType {
	if m != nil {
		return m.MajorType
	}
	return types.MajorType__
}

func (m *Account) GetMajorCategory() types.MajorCategory {
	if m != nil {
		return m.MajorCategory
	}
	return types.MajorCategory__
}

func (m *Account) GetMaturityDate() string {
	if m != nil {
		return m.MaturityDate
	}
	return ""
}

func (m *Account) GetNextPaymentDueDate() string {
	if m != nil {
		return m.NextPaymentDueDate
	}
	return ""
}

func (m *Account) GetOwnerName() string {
	if m != nil {
		return m.OwnerName
	}
	return ""
}

func (m *Account) GetStartDate() string {
	if m != nil {
		return m.StartDate
	}
	return ""
}

// GetAccountRequest is the request envelope to get an account by its identifier.
type GetAccountRequest struct {
	AccountID            string   `protobuf:"bytes,1,opt,name=AccountID,json=account_id,proto3" json:"AccountID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountRequest) Reset()         { *m = GetAccountRequest{} }
func (m *GetAccountRequest) String() string { return proto.CompactTextString(m) }
func (*GetAccountRequest) ProtoMessage()    {}
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_all_f3d029296c464da3, []int{1}
}
func (m *GetAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountRequest.Unmarshal(m, b)
}
func (m *GetAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountRequest.Marshal(b, m, deterministic)
}
func (dst *GetAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountRequest.Merge(dst, src)
}
func (m *GetAccountRequest) XXX_Size() int {
	return xxx_messageInfo_GetAccountRequest.Size(m)
}
func (m *GetAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountRequest proto.InternalMessageInfo

func (m *GetAccountRequest) GetAccountID() string {
	if m != nil {
		return m.AccountID
	}
	return ""
}

// GetAccountsRequest is the request envelope to get a list of filtered accounts.
type GetAccountsRequest struct {
	// NextStartingIndex is a cursor for pagination. It's an AccountID that defines
	// the current place in the total list of Accounts.
	NextStartingIndex    string   `protobuf:"bytes,1,opt,name=NextStartingIndex,json=next_starting_index,proto3" json:"NextStartingIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountsRequest) Reset()         { *m = GetAccountsRequest{} }
func (m *GetAccountsRequest) String() string { return proto.CompactTextString(m) }
func (*GetAccountsRequest) ProtoMessage()    {}
func (*GetAccountsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_all_f3d029296c464da3, []int{2}
}
func (m *GetAccountsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountsRequest.Unmarshal(m, b)
}
func (m *GetAccountsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountsRequest.Marshal(b, m, deterministic)
}
func (dst *GetAccountsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountsRequest.Merge(dst, src)
}
func (m *GetAccountsRequest) XXX_Size() int {
	return xxx_messageInfo_GetAccountsRequest.Size(m)
}
func (m *GetAccountsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountsRequest proto.InternalMessageInfo

func (m *GetAccountsRequest) GetNextStartingIndex() string {
	if m != nil {
		return m.NextStartingIndex
	}
	return ""
}

// GetAccountsResponse wraps the list of accounts.
type GetAccountsResponse struct {
	// Result is a list containing up to 20 Accounts.
	Result []*Account `protobuf:"bytes,1,rep,name=Result,json=result,proto3" json:"Result,omitempty"`
	// HasMore indicates if there are more accounts available.
	HasMore              bool     `protobuf:"varint,2,opt,name=HasMore,json=has_more,proto3" json:"HasMore,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountsResponse) Reset()         { *m = GetAccountsResponse{} }
func (m *GetAccountsResponse) String() string { return proto.CompactTextString(m) }
func (*GetAccountsResponse) ProtoMessage()    {}
func (*GetAccountsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_all_f3d029296c464da3, []int{3}
}
func (m *GetAccountsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountsResponse.Unmarshal(m, b)
}
func (m *GetAccountsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountsResponse.Marshal(b, m, deterministic)
}
func (dst *GetAccountsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountsResponse.Merge(dst, src)
}
func (m *GetAccountsResponse) XXX_Size() int {
	return xxx_messageInfo_GetAccountsResponse.Size(m)
}
func (m *GetAccountsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountsResponse proto.InternalMessageInfo

func (m *GetAccountsResponse) GetResult() []*Account {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *GetAccountsResponse) GetHasMore() bool {
	if m != nil {
		return m.HasMore
	}
	return false
}

// TODO: add comment.
type AccountRole struct {
	// TODO: add comment.
	EntityNumber string `protobuf:"bytes,1,opt,name=EntityNumber,json=entity_number,proto3" json:"EntityNumber,omitempty"`
	// TODO: add comment.
	EntityType EntityType `protobuf:"varint,2,opt,name=EntityType,json=entity_type,proto3,enum=accounts.EntityType" json:"EntityType,omitempty"`
	// TODO: add comment.
	Role                 string   `protobuf:"bytes,3,opt,name=Role,json=role,proto3" json:"Role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountRole) Reset()         { *m = AccountRole{} }
func (m *AccountRole) String() string { return proto.CompactTextString(m) }
func (*AccountRole) ProtoMessage()    {}
func (*AccountRole) Descriptor() ([]byte, []int) {
	return fileDescriptor_all_f3d029296c464da3, []int{4}
}
func (m *AccountRole) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountRole.Unmarshal(m, b)
}
func (m *AccountRole) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountRole.Marshal(b, m, deterministic)
}
func (dst *AccountRole) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountRole.Merge(dst, src)
}
func (m *AccountRole) XXX_Size() int {
	return xxx_messageInfo_AccountRole.Size(m)
}
func (m *AccountRole) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountRole.DiscardUnknown(m)
}

var xxx_messageInfo_AccountRole proto.InternalMessageInfo

func (m *AccountRole) GetEntityNumber() string {
	if m != nil {
		return m.EntityNumber
	}
	return ""
}

func (m *AccountRole) GetEntityType() EntityType {
	if m != nil {
		return m.EntityType
	}
	return EntityType__
}

func (m *AccountRole) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

// TODO: add comment.
type DebitTransaction struct {
	// TODO: add comment.
	Amount string `protobuf:"bytes,1,opt,name=Amount,json=amount,proto3" json:"Amount,omitempty"`
	// TODO: add comment.
	DebitAccount string `protobuf:"bytes,2,opt,name=DebitAccount,json=debit_account,proto3" json:"DebitAccount,omitempty"`
	// TODO: add comment.
	ExchangeRate string `protobuf:"bytes,3,opt,name=ExchangeRate,json=exchange_rate,proto3" json:"ExchangeRate,omitempty"`
	// TODO: add comment.
	IsFx                 bool     `protobuf:"varint,4,opt,name=IsFx,json=is_fx,proto3" json:"IsFx,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DebitTransaction) Reset()         { *m = DebitTransaction{} }
func (m *DebitTransaction) String() string { return proto.CompactTextString(m) }
func (*DebitTransaction) ProtoMessage()    {}
func (*DebitTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_all_f3d029296c464da3, []int{5}
}
func (m *DebitTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DebitTransaction.Unmarshal(m, b)
}
func (m *DebitTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DebitTransaction.Marshal(b, m, deterministic)
}
func (dst *DebitTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DebitTransaction.Merge(dst, src)
}
func (m *DebitTransaction) XXX_Size() int {
	return xxx_messageInfo_DebitTransaction.Size(m)
}
func (m *DebitTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_DebitTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_DebitTransaction proto.InternalMessageInfo

func (m *DebitTransaction) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *DebitTransaction) GetDebitAccount() string {
	if m != nil {
		return m.DebitAccount
	}
	return ""
}

func (m *DebitTransaction) GetExchangeRate() string {
	if m != nil {
		return m.ExchangeRate
	}
	return ""
}

func (m *DebitTransaction) GetIsFx() bool {
	if m != nil {
		return m.IsFx
	}
	return false
}

// CreateAccountRequest wraps all required fields for an account creation.
type CreateAccountRequest struct {
	// AccountID is the identifier of the account.
	AccountID string `protobuf:"bytes,1,opt,name=AccountID,json=account_id,proto3" json:"AccountID,omitempty"`
	// TODO: add comment.
	Description string `protobuf:"bytes,2,opt,name=Description,json=description,proto3" json:"Description,omitempty"`
	// TODO: add comment.
	AccountRoles []*AccountRole `protobuf:"bytes,3,rep,name=AccountRoles,json=account_roles,proto3" json:"AccountRoles,omitempty"`
	// TODO: add comment.
	Branch string `protobuf:"bytes,4,opt,name=Branch,json=branch,proto3" json:"Branch,omitempty"`
	// TODO: add comment.
	Customer string `protobuf:"bytes,5,opt,name=Customer,json=customer,proto3" json:"Customer,omitempty"`
	// TODO: add comment.
	DebitTransaction *DebitTransaction `protobuf:"bytes,6,opt,name=DebitTransaction,json=debit_transaction,proto3" json:"DebitTransaction,omitempty"`
	// TODO: add comment.
	InterestRate string `protobuf:"bytes,7,opt,name=InterestRate,json=interest_rate,proto3" json:"InterestRate,omitempty"`
	// MajorType is the type of the account.
	MajorType types.MajorType `protobuf:"varint,8,opt,name=MajorType,json=major_type,proto3,enum=types.MajorType" json:"MajorType,omitempty"`
	// TODO: add comment.
	MaturityDate string `protobuf:"bytes,9,opt,name=MaturityDate,json=maturity_date,proto3" json:"MaturityDate,omitempty"`
	// TODO: add comment.
	Minor                string   `protobuf:"bytes,10,opt,name=Minor,json=minor,proto3" json:"Minor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountRequest) Reset()         { *m = CreateAccountRequest{} }
func (m *CreateAccountRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAccountRequest) ProtoMessage()    {}
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_all_f3d029296c464da3, []int{6}
}
func (m *CreateAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountRequest.Unmarshal(m, b)
}
func (m *CreateAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountRequest.Marshal(b, m, deterministic)
}
func (dst *CreateAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountRequest.Merge(dst, src)
}
func (m *CreateAccountRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAccountRequest.Size(m)
}
func (m *CreateAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountRequest proto.InternalMessageInfo

func (m *CreateAccountRequest) GetAccountID() string {
	if m != nil {
		return m.AccountID
	}
	return ""
}

func (m *CreateAccountRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateAccountRequest) GetAccountRoles() []*AccountRole {
	if m != nil {
		return m.AccountRoles
	}
	return nil
}

func (m *CreateAccountRequest) GetBranch() string {
	if m != nil {
		return m.Branch
	}
	return ""
}

func (m *CreateAccountRequest) GetCustomer() string {
	if m != nil {
		return m.Customer
	}
	return ""
}

func (m *CreateAccountRequest) GetDebitTransaction() *DebitTransaction {
	if m != nil {
		return m.DebitTransaction
	}
	return nil
}

func (m *CreateAccountRequest) GetInterestRate() string {
	if m != nil {
		return m.InterestRate
	}
	return ""
}

func (m *CreateAccountRequest) GetMajorType() types.MajorType {
	if m != nil {
		return m.MajorType
	}
	return types.MajorType__
}

func (m *CreateAccountRequest) GetMaturityDate() string {
	if m != nil {
		return m.MaturityDate
	}
	return ""
}

func (m *CreateAccountRequest) GetMinor() string {
	if m != nil {
		return m.Minor
	}
	return ""
}

// CreateAccountResponse is the response envelope for an account creation.
type CreateAccountResponse struct {
	// AccountID is the unique identifier of the newly created account.
	AccountID string `protobuf:"bytes,1,opt,name=AccountID,json=account_id,proto3" json:"AccountID,omitempty"`
	// CreditTransactionNumber is the transaction number of the credited account.
	CreditTransactionNumber string `protobuf:"bytes,2,opt,name=CreditTransactionNumber,json=credit_transaction_number,proto3" json:"CreditTransactionNumber,omitempty"`
	// DebitTransactionNumber is the transaction number of the debited account.
	DebitTransactionNumber string `protobuf:"bytes,3,opt,name=DebitTransactionNumber,json=debit_transaction_number,proto3" json:"DebitTransactionNumber,omitempty"`
	// MajorType is the type of the account.
	MajorType types.MajorType `protobuf:"varint,4,opt,name=MajorType,json=major_type,proto3,enum=types.MajorType" json:"MajorType,omitempty"`
	// TODO: add comment.
	Minor                string   `protobuf:"bytes,5,opt,name=Minor,json=minor,proto3" json:"Minor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountResponse) Reset()         { *m = CreateAccountResponse{} }
func (m *CreateAccountResponse) String() string { return proto.CompactTextString(m) }
func (*CreateAccountResponse) ProtoMessage()    {}
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_all_f3d029296c464da3, []int{7}
}
func (m *CreateAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountResponse.Unmarshal(m, b)
}
func (m *CreateAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountResponse.Marshal(b, m, deterministic)
}
func (dst *CreateAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountResponse.Merge(dst, src)
}
func (m *CreateAccountResponse) XXX_Size() int {
	return xxx_messageInfo_CreateAccountResponse.Size(m)
}
func (m *CreateAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountResponse proto.InternalMessageInfo

func (m *CreateAccountResponse) GetAccountID() string {
	if m != nil {
		return m.AccountID
	}
	return ""
}

func (m *CreateAccountResponse) GetCreditTransactionNumber() string {
	if m != nil {
		return m.CreditTransactionNumber
	}
	return ""
}

func (m *CreateAccountResponse) GetDebitTransactionNumber() string {
	if m != nil {
		return m.DebitTransactionNumber
	}
	return ""
}

func (m *CreateAccountResponse) GetMajorType() types.MajorType {
	if m != nil {
		return m.MajorType
	}
	return types.MajorType__
}

func (m *CreateAccountResponse) GetMinor() string {
	if m != nil {
		return m.Minor
	}
	return ""
}

// UpdateAccountRequest wraps all fields available for update.
type UpdateAccountRequest struct {
	// AccountID is the unique identifier of the account to update.
	AccountID string `protobuf:"bytes,1,opt,name=AccountID,json=account_id,proto3" json:"AccountID,omitempty"`
	// TODO: add comment.
	Description          string   `protobuf:"bytes,2,opt,name=Description,json=description,proto3" json:"Description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAccountRequest) Reset()         { *m = UpdateAccountRequest{} }
func (m *UpdateAccountRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateAccountRequest) ProtoMessage()    {}
func (*UpdateAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_all_f3d029296c464da3, []int{8}
}
func (m *UpdateAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAccountRequest.Unmarshal(m, b)
}
func (m *UpdateAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAccountRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAccountRequest.Merge(dst, src)
}
func (m *UpdateAccountRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateAccountRequest.Size(m)
}
func (m *UpdateAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAccountRequest proto.InternalMessageInfo

func (m *UpdateAccountRequest) GetAccountID() string {
	if m != nil {
		return m.AccountID
	}
	return ""
}

func (m *UpdateAccountRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

// DeleteAccountRequest is the request envelope to delete an account.
type DeleteAccountRequest struct {
	// AccountID is the unique identifier of the account to delete.
	AccountID            string   `protobuf:"bytes,1,opt,name=AccountID,json=account_id,proto3" json:"AccountID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAccountRequest) Reset()         { *m = DeleteAccountRequest{} }
func (m *DeleteAccountRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAccountRequest) ProtoMessage()    {}
func (*DeleteAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_all_f3d029296c464da3, []int{9}
}
func (m *DeleteAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAccountRequest.Unmarshal(m, b)
}
func (m *DeleteAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAccountRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAccountRequest.Merge(dst, src)
}
func (m *DeleteAccountRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAccountRequest.Size(m)
}
func (m *DeleteAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAccountRequest proto.InternalMessageInfo

func (m *DeleteAccountRequest) GetAccountID() string {
	if m != nil {
		return m.AccountID
	}
	return ""
}

func init() {
	proto.RegisterType((*Account)(nil), "accounts.Account")
	proto.RegisterType((*GetAccountRequest)(nil), "accounts.GetAccountRequest")
	proto.RegisterType((*GetAccountsRequest)(nil), "accounts.GetAccountsRequest")
	proto.RegisterType((*GetAccountsResponse)(nil), "accounts.GetAccountsResponse")
	proto.RegisterType((*AccountRole)(nil), "accounts.AccountRole")
	proto.RegisterType((*DebitTransaction)(nil), "accounts.DebitTransaction")
	proto.RegisterType((*CreateAccountRequest)(nil), "accounts.CreateAccountRequest")
	proto.RegisterType((*CreateAccountResponse)(nil), "accounts.CreateAccountResponse")
	proto.RegisterType((*UpdateAccountRequest)(nil), "accounts.UpdateAccountRequest")
	proto.RegisterType((*DeleteAccountRequest)(nil), "accounts.DeleteAccountRequest")
	proto.RegisterEnum("accounts.EntityType", EntityType_name, EntityType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountServiceClient is the client API for AccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountServiceClient interface {
	// GetAccount retrieves the detail of an account, selected by its id.
	GetAccount(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*Account, error)
	// GetAccounts returns a list containing up to 20 accounts.
	GetAccounts(ctx context.Context, in *GetAccountsRequest, opts ...grpc.CallOption) (*GetAccountsResponse, error)
	// CreateAccount creates a new account and return its id.
	CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountResponse, error)
	// UpdateAccount updates an account.
	UpdateAccount(ctx context.Context, in *UpdateAccountRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// DeleteAccount deletes an account.
	DeleteAccount(ctx context.Context, in *DeleteAccountRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type accountServiceClient struct {
	cc *grpc.ClientConn
}

func NewAccountServiceClient(cc *grpc.ClientConn) AccountServiceClient {
	return &accountServiceClient{cc}
}

func (c *accountServiceClient) GetAccount(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*Account, error) {
	out := new(Account)
	err := c.cc.Invoke(ctx, "/accounts.AccountService/GetAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GetAccounts(ctx context.Context, in *GetAccountsRequest, opts ...grpc.CallOption) (*GetAccountsResponse, error) {
	out := new(GetAccountsResponse)
	err := c.cc.Invoke(ctx, "/accounts.AccountService/GetAccounts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountResponse, error) {
	out := new(CreateAccountResponse)
	err := c.cc.Invoke(ctx, "/accounts.AccountService/CreateAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) UpdateAccount(ctx context.Context, in *UpdateAccountRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/accounts.AccountService/UpdateAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) DeleteAccount(ctx context.Context, in *DeleteAccountRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/accounts.AccountService/DeleteAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServiceServer is the server API for AccountService service.
type AccountServiceServer interface {
	// GetAccount retrieves the detail of an account, selected by its id.
	GetAccount(context.Context, *GetAccountRequest) (*Account, error)
	// GetAccounts returns a list containing up to 20 accounts.
	GetAccounts(context.Context, *GetAccountsRequest) (*GetAccountsResponse, error)
	// CreateAccount creates a new account and return its id.
	CreateAccount(context.Context, *CreateAccountRequest) (*CreateAccountResponse, error)
	// UpdateAccount updates an account.
	UpdateAccount(context.Context, *UpdateAccountRequest) (*empty.Empty, error)
	// DeleteAccount deletes an account.
	DeleteAccount(context.Context, *DeleteAccountRequest) (*empty.Empty, error)
}

func RegisterAccountServiceServer(s *grpc.Server, srv AccountServiceServer) {
	s.RegisterService(&_AccountService_serviceDesc, srv)
}

func _AccountService_GetAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accounts.AccountService/GetAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetAccount(ctx, req.(*GetAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_GetAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accounts.AccountService/GetAccounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetAccounts(ctx, req.(*GetAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accounts.AccountService/CreateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).CreateAccount(ctx, req.(*CreateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_UpdateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).UpdateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accounts.AccountService/UpdateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).UpdateAccount(ctx, req.(*UpdateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_DeleteAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).DeleteAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accounts.AccountService/DeleteAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).DeleteAccount(ctx, req.(*DeleteAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccountService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "accounts.AccountService",
	HandlerType: (*AccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAccount",
			Handler:    _AccountService_GetAccount_Handler,
		},
		{
			MethodName: "GetAccounts",
			Handler:    _AccountService_GetAccounts_Handler,
		},
		{
			MethodName: "CreateAccount",
			Handler:    _AccountService_CreateAccount_Handler,
		},
		{
			MethodName: "UpdateAccount",
			Handler:    _AccountService_UpdateAccount_Handler,
		},
		{
			MethodName: "DeleteAccount",
			Handler:    _AccountService_DeleteAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "command-line-arguments/all.proto",
}

func init() {
	proto.RegisterFile("command-line-arguments/all.proto", fileDescriptor_all_f3d029296c464da3)
}

var fileDescriptor_all_f3d029296c464da3 = []byte{
	// 2133 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x58, 0x4d, 0x6c, 0x23, 0x49,
	0xf5, 0x77, 0xdb, 0x49, 0xc6, 0xa9, 0x7c, 0x6c, 0x52, 0xc9, 0xcc, 0xdf, 0x7f, 0xef, 0xce, 0x4c,
	0x6d, 0x10, 0x4b, 0x26, 0x33, 0x69, 0x3b, 0xde, 0x59, 0x84, 0x82, 0x56, 0xe0, 0x24, 0x93, 0xd9,
	0x8c, 0xe6, 0x23, 0xf2, 0xcc, 0x2e, 0xcb, 0x5e, 0xac, 0x72, 0xf7, 0xb3, 0xdd, 0x3b, 0xdd, 0x55,
	0xa6, 0xaa, 0x3a, 0x89, 0x59, 0x21, 0xa1, 0x15, 0x87, 0x11, 0x5c, 0x56, 0xe1, 0xc4, 0x71, 0xb9,
	0xed, 0x8d, 0x1b, 0x7b, 0x85, 0x23, 0x27, 0x24, 0x0e, 0x20, 0x38, 0x21, 0x81, 0xc4, 0x61, 0xc5,
	0x11, 0x71, 0x03, 0x55, 0x75, 0xb7, 0xdd, 0x76, 0x77, 0x94, 0x1d, 0x90, 0xb8, 0xcc, 0xc4, 0xf5,
	0x7e, 0xef, 0xd5, 0x7b, 0xbf, 0xf7, 0xd5, 0xdd, 0x88, 0x38, 0x3c, 0x08, 0x28, 0x73, 0xb7, 0x7d,
	0x8f, 0xc1, 0x36, 0x15, 0xbd, 0x30, 0x00, 0xa6, 0x64, 0x8d, 0xfa, 0xbe, 0x3d, 0x10, 0x5c, 0x71,
	0x5c, 0xa6, 0x8e, 0xc3, 0x43, 0xa6, 0x64, 0xf5, 0xb5, 0x1e, 0xe7, 0x3d, 0x1f, 0x6a, 0x74, 0xe0,
	0xd5, 0x28, 0x63, 0x5c, 0x51, 0xe5, 0x71, 0x26, 0x23, 0x5c, 0xf5, 0x8e, 0xf9, 0xcf, 0xd9, 0xee,
	0x01, 0xdb, 0x96, 0xa7, 0xb4, 0xd7, 0x03, 0x51, 0xe3, 0x03, 0x83, 0xc8, 0x41, 0xbf, 0x1a, 0xdb,
	0x32, 0xbf, 0x3a, 0x61, 0xb7, 0x06, 0xc1, 0x40, 0x0d, 0x63, 0x61, 0xbd, 0xe7, 0xa9, 0x7e, 0xd8,
	0xb1, 0x1d, 0x1e, 0xd4, 0xf8, 0x00, 0x58, 0x87, 0xb2, 0xe7, 0xb5, 0x5e, 0x98, 0xfc, 0x73, 0xb2,
	0x53, 0x53, 0xc3, 0x01, 0xa4, 0x9c, 0xdc, 0xf8, 0xcd, 0x3c, 0xba, 0xd2, 0x8c, 0xfc, 0xc4, 0xb7,
	0xd0, 0x7c, 0xfc, 0xe7, 0xd1, 0x41, 0xc5, 0x22, 0xd6, 0xe6, 0xfc, 0x1e, 0x2a, 0x17, 0x2a, 0x85,
	0xcd, 0x42, 0xbd, 0x70, 0x5c, 0x68, 0xa1, 0x38, 0x9e, 0xb6, 0xe7, 0xe2, 0x0d, 0x34, 0xb7, 0x27,
	0x28, 0x73, 0xfa, 0x95, 0x62, 0x06, 0x37, 0xd7, 0x31, 0x12, 0x7c, 0x1b, 0xa1, 0x08, 0xf3, 0x98,
	0x06, 0x50, 0x29, 0x65, 0x70, 0x0b, 0x11, 0xae, 0xcd, 0x68, 0x00, 0xda, 0xe0, 0x53, 0x45, 0x55,
	0x28, 0x2b, 0x33, 0x59, 0x83, 0xd2, 0x48, 0xf0, 0x33, 0x74, 0xbd, 0xe9, 0x38, 0x22, 0x04, 0xf7,
	0x88, 0x29, 0x10, 0x20, 0x55, 0x53, 0x3d, 0xa2, 0x2a, 0x14, 0x9e, 0x1a, 0x1e, 0x50, 0x05, 0x95,
	0xd9, 0x8c, 0xea, 0xeb, 0x34, 0x52, 0x68, 0x7b, 0xb1, 0x46, 0x9b, 0xaa, 0x76, 0x10, 0xeb, 0xb4,
	0x5d, 0xaa, 0x00, 0x7f, 0x03, 0xcd, 0x37, 0x03, 0x1d, 0xd7, 0x41, 0x08, 0x95, 0x39, 0x62, 0x6d,
	0x2e, 0x34, 0x96, 0x6c, 0x43, 0x93, 0x1d, 0x9d, 0x4f, 0x91, 0x60, 0xce, 0xda, 0x6e, 0x08, 0xf8,
	0x10, 0xad, 0x34, 0x4f, 0xa8, 0xe7, 0xd3, 0x8e, 0x0f, 0x7b, 0xd4, 0xa7, 0xcc, 0x81, 0xca, 0x95,
	0xcb, 0x0c, 0xac, 0xd2, 0x44, 0xa5, 0xdd, 0x89, 0x74, 0xf0, 0xb7, 0xd1, 0xfa, 0xc8, 0xce, 0xbe,
	0x00, 0xd7, 0x53, 0x0f, 0xbd, 0xc0, 0x53, 0x95, 0x72, 0x26, 0x9c, 0x6b, 0x63, 0x65, 0xc7, 0x00,
	0xdb, 0xbe, 0x46, 0x6a, 0x0b, 0xfb, 0x7d, 0x70, 0x9e, 0x7b, 0xac, 0x97, 0x50, 0xd3, 0xd2, 0x84,
	0xcc, 0x67, 0x2d, 0x38, 0x31, 0x6e, 0xcc, 0x88, 0xd0, 0x2c, 0xd4, 0xd0, 0xe2, 0x3e, 0x67, 0x4a,
	0x50, 0x47, 0x19, 0x2a, 0x51, 0x46, 0x73, 0xc9, 0x89, 0xe5, 0x11, 0x6d, 0xdb, 0x68, 0x21, 0xed,
	0xeb, 0x42, 0x06, 0xbf, 0x38, 0xe1, 0xe1, 0x01, 0xba, 0xb6, 0x1f, 0x0a, 0x01, 0x4c, 0x4d, 0xa5,
	0xb0, 0xb2, 0x98, 0xd1, 0xac, 0x38, 0x11, 0xb2, 0x3d, 0x9d, 0x3c, 0xbc, 0x87, 0x96, 0x63, 0x2b,
	0x09, 0xdf, 0x4b, 0x97, 0xf1, 0xfd, 0x4a, 0x62, 0x2c, 0x61, 0x5b, 0x3b, 0x1e, 0x1d, 0x3d, 0x03,
	0x11, 0x54, 0x96, 0x73, 0x1c, 0x8f, 0x35, 0x14, 0x88, 0x00, 0x7f, 0x15, 0x5d, 0x39, 0x08, 0xc1,
	0x70, 0xf2, 0x4a, 0x06, 0x5a, 0x76, 0x43, 0x88, 0xe8, 0xa8, 0xa1, 0xc5, 0x09, 0xe6, 0x57, 0xb2,
	0xfc, 0x4d, 0x12, 0xfe, 0x4d, 0x34, 0xff, 0x88, 0x7e, 0xc8, 0xc5, 0xb3, 0xe1, 0x00, 0x2a, 0xab,
	0xc4, 0xda, 0x5c, 0x6e, 0xac, 0xc4, 0x51, 0x8c, 0xce, 0x27, 0x2b, 0x2f, 0xd0, 0xc7, 0x6d, 0x0d,
	0xc1, 0xf7, 0xd1, 0x92, 0x01, 0xed, 0x53, 0x05, 0x3d, 0x2e, 0x86, 0x15, 0x6c, 0x0c, 0xac, 0xa7,
	0x0d, 0x24, 0xb2, 0x09, 0x23, 0xcb, 0x91, 0x11, 0x27, 0x96, 0x69, 0xb7, 0x27, 0x3a, 0x68, 0x2d,
	0xeb, 0xf6, 0x64, 0xb7, 0xbc, 0x8d, 0xf0, 0x63, 0x38, 0x53, 0xc7, 0x74, 0xa8, 0xc7, 0x5d, 0xc2,
	0xcc, 0x7a, 0x46, 0xed, 0x2a, 0x83, 0x33, 0xd5, 0x1e, 0x44, 0xb0, 0xf6, 0x88, 0xa6, 0x5b, 0x68,
	0xfe, 0xc9, 0x29, 0x03, 0x61, 0x46, 0xc2, 0xd5, 0xec, 0x88, 0xe1, 0x5a, 0x18, 0x4d, 0x84, 0x5b,
	0x68, 0xfe, 0xa9, 0xa2, 0x22, 0x2a, 0xc7, 0x6b, 0x59, 0xa8, 0xd4, 0x42, 0x63, 0x75, 0x77, 0xae,
	0x5c, 0x58, 0x29, 0x54, 0x0a, 0x1b, 0x87, 0x68, 0xf5, 0x3e, 0xa8, 0x78, 0x86, 0xb5, 0xe0, 0x7b,
	0xa1, 0xae, 0x99, 0x2f, 0x3f, 0xd5, 0x46, 0x76, 0xde, 0x47, 0x78, 0x6c, 0x47, 0x26, 0x86, 0x76,
	0xd1, 0xaa, 0x0e, 0xdd, 0x38, 0x65, 0x1a, 0xcd, 0x85, 0xb3, 0x1c, 0x83, 0x6b, 0x26, 0x72, 0x19,
	0xa3, 0xda, 0x9e, 0x86, 0x8d, 0x2c, 0x7f, 0x84, 0xd6, 0x26, 0x2c, 0xcb, 0x01, 0x67, 0x12, 0xf0,
	0x5b, 0x68, 0xae, 0x05, 0x32, 0xf4, 0x55, 0xc5, 0x22, 0xa5, 0xcd, 0x85, 0xc6, 0xaa, 0x9d, 0xec,
	0x0e, 0x3b, 0xc6, 0x4e, 0x0e, 0x44, 0x61, 0xc0, 0xba, 0x36, 0xdf, 0xa1, 0xf2, 0x11, 0x17, 0x60,
	0xc6, 0x70, 0x79, 0xb2, 0x36, 0xfb, 0x54, 0xb6, 0x03, 0x2e, 0xc6, 0xf4, 0x7c, 0x66, 0xa1, 0x85,
	0x84, 0x1c, 0xee, 0x9b, 0x9a, 0xbd, 0xc7, 0x94, 0xa7, 0x86, 0x8f, 0xc3, 0xa0, 0x03, 0x22, 0x27,
	0x96, 0x25, 0x30, 0xf2, 0x36, 0x33, 0x00, 0xdc, 0x44, 0x28, 0x52, 0x30, 0x45, 0x5b, 0x8c, 0x6b,
	0x6e, 0xe4, 0xea, 0x58, 0x36, 0x39, 0xe7, 0x63, 0x23, 0xa6, 0x72, 0x6f, 0xa0, 0x19, 0x7d, 0x77,
	0xce, 0x3a, 0x98, 0x11, 0xdc, 0x1f, 0xfb, 0xfa, 0x2b, 0x0b, 0xad, 0x1c, 0x40, 0xc7, 0x53, 0xcf,
	0x04, 0x65, 0x92, 0x3a, 0x7a, 0x05, 0xea, 0x25, 0x11, 0x75, 0x78, 0x8e, 0xab, 0x73, 0xd1, 0x60,
	0xd6, 0x41, 0x19, 0xbd, 0x38, 0xd0, 0x9c, 0xfd, 0xb4, 0xe4, 0x6a, 0x79, 0x3b, 0x76, 0xdb, 0xb0,
	0x70, 0xe6, 0xf4, 0x29, 0xeb, 0x81, 0xe9, 0xdc, 0x52, 0x0e, 0x0b, 0xb1, 0x3c, 0xea, 0xdc, 0x9b,
	0x68, 0xe6, 0x48, 0x1e, 0x9e, 0x99, 0x45, 0x35, 0x49, 0xf9, 0xac, 0x27, 0xdb, 0xdd, 0x71, 0xb2,
	0x3f, 0x9d, 0x41, 0xeb, 0xfb, 0x02, 0xa8, 0x82, 0xff, 0xb8, 0x24, 0xf1, 0x1d, 0xb4, 0x70, 0x00,
	0xd2, 0x11, 0x9e, 0x79, 0x20, 0xc8, 0x89, 0x66, 0xc1, 0x1d, 0x8b, 0xf1, 0x21, 0x5a, 0x4c, 0x25,
	0x58, 0x56, 0x4a, 0xa6, 0x9a, 0xae, 0x66, 0xaa, 0x49, 0x4b, 0x27, 0x43, 0x4c, 0xae, 0xd4, 0x49,
	0x90, 0xa9, 0xf5, 0x3e, 0x73, 0xe1, 0x7a, 0x7f, 0x03, 0x95, 0xf7, 0x43, 0xa9, 0x78, 0x00, 0x22,
	0x67, 0xf1, 0x96, 0x9d, 0x58, 0x86, 0x9f, 0x66, 0x13, 0x19, 0xaf, 0xd9, 0xea, 0xd8, 0xaf, 0x69,
	0xc4, 0xe4, 0xca, 0x8c, 0x12, 0xa6, 0x52, 0x95, 0x30, 0x3d, 0x6e, 0xaf, 0xbc, 0xd4, 0xb8, 0x2d,
	0xbf, 0xe4, 0xb8, 0x9d, 0x9e, 0x92, 0xf3, 0x97, 0x4d, 0x49, 0x82, 0x66, 0x1f, 0x79, 0x8c, 0x8b,
	0x9c, 0x35, 0x3a, 0x1b, 0x68, 0xc1, 0xa8, 0x46, 0x7e, 0x59, 0x44, 0x57, 0xa7, 0x6a, 0x24, 0x9e,
	0x09, 0x2f, 0x51, 0x24, 0x87, 0xe8, 0xff, 0xa2, 0x5d, 0x9c, 0x62, 0x30, 0xee, 0xe9, 0x6c, 0xc1,
	0xfc, 0x7f, 0xbc, 0x97, 0x53, 0x74, 0x26, 0xfd, 0x7d, 0x80, 0xae, 0x4d, 0x27, 0x22, 0x36, 0x93,
	0x6d, 0x8a, 0x4a, 0x26, 0x29, 0x89, 0x95, 0x09, 0xaa, 0x67, 0x5e, 0x92, 0xea, 0x11, 0x73, 0xb3,
	0x97, 0x31, 0x77, 0x8a, 0xd6, 0xdf, 0x1d, 0xb8, 0xff, 0xbb, 0xe6, 0x1a, 0x5d, 0x7c, 0x84, 0xd6,
	0x0f, 0xc0, 0x87, 0xff, 0xe2, 0xe2, 0xc4, 0xd4, 0xd6, 0xd7, 0xd3, 0x03, 0x15, 0xcf, 0x23, 0xab,
	0xbd, 0x52, 0xa8, 0x16, 0xcb, 0x05, 0xbc, 0x88, 0x66, 0x8e, 0x41, 0xc8, 0x15, 0xcb, 0xfc, 0x5a,
	0x40, 0xa5, 0x27, 0xa2, 0xb7, 0x52, 0xd4, 0x3f, 0xaa, 0xc5, 0x4a, 0xa1, 0xf1, 0x8f, 0x45, 0xb4,
	0x1c, 0xdf, 0xf5, 0x14, 0xc4, 0x89, 0xe7, 0x00, 0xfe, 0xa2, 0x88, 0xd0, 0x78, 0xb5, 0xe0, 0x57,
	0xc7, 0xbd, 0x95, 0x59, 0x89, 0xd5, 0xec, 0x7a, 0xd9, 0xf8, 0xac, 0x78, 0xde, 0xfc, 0x97, 0x35,
	0x7e, 0x17, 0x58, 0x6b, 0x81, 0x12, 0x1e, 0x9c, 0x00, 0xa1, 0x8c, 0xc4, 0xe8, 0xea, 0xc3, 0xe4,
	0x50, 0x12, 0xea, 0xfb, 0xc4, 0xa5, 0x8a, 0x92, 0xae, 0xe0, 0x41, 0x0a, 0x73, 0x87, 0x48, 0xf0,
	0xc1, 0x51, 0xe0, 0x92, 0xce, 0x90, 0xa8, 0x3e, 0x90, 0x71, 0xd8, 0x64, 0xc8, 0x43, 0x22, 0xc3,
	0xc1, 0xc0, 0xf7, 0xc0, 0xb5, 0x1f, 0x3c, 0x40, 0xa5, 0x46, 0xbd, 0x8e, 0xf7, 0xd1, 0x8d, 0xd8,
	0x2f, 0x02, 0x67, 0xe0, 0x84, 0x5a, 0x55, 0x86, 0x8e, 0x03, 0x52, 0x76, 0x43, 0xdf, 0x1f, 0xda,
	0xf8, 0x75, 0x74, 0xb3, 0x7a, 0xfd, 0x2b, 0x35, 0x17, 0xba, 0x1e, 0xf3, 0xe2, 0xf7, 0xa2, 0xd8,
	0xff, 0xd8, 0xdd, 0x07, 0x3b, 0xa8, 0x74, 0xb7, 0x7e, 0x17, 0x6f, 0xa1, 0xcd, 0x16, 0xa8, 0x50,
	0x30, 0x70, 0xc9, 0x69, 0x1f, 0x98, 0x71, 0x40, 0x80, 0xe4, 0xa1, 0x70, 0x80, 0x78, 0x92, 0x30,
	0xae, 0x48, 0x97, 0x87, 0xcc, 0xb5, 0x3b, 0x18, 0xad, 0xa0, 0xb9, 0x27, 0xcd, 0x50, 0xf5, 0x1b,
	0x78, 0x0e, 0xcd, 0x08, 0xa0, 0xee, 0xc7, 0xbf, 0xfb, 0xcb, 0x4f, 0x8b, 0x55, 0x5c, 0xd1, 0x2f,
	0x4a, 0xc9, 0x0d, 0xb5, 0x8f, 0x46, 0x49, 0xfd, 0xc1, 0x8b, 0x62, 0xe1, 0x93, 0xa2, 0xc9, 0x27,
	0xfe, 0x53, 0x09, 0x2d, 0xa4, 0x36, 0x39, 0x7e, 0x2d, 0x8f, 0xef, 0xe4, 0xd1, 0xa1, 0x7a, 0xfd,
	0x02, 0x69, 0xd4, 0xea, 0x1b, 0x3f, 0x2e, 0x9d, 0x37, 0xbf, 0x28, 0x8e, 0xc9, 0x5f, 0x7d, 0xe8,
	0x49, 0x65, 0x28, 0x1e, 0xbd, 0x42, 0xfe, 0xd9, 0x8a, 0x02, 0x93, 0x84, 0x12, 0x5f, 0x4b, 0xf5,
	0xd3, 0x38, 0xf5, 0x98, 0xc7, 0x7a, 0x24, 0x1c, 0x10, 0xc5, 0x49, 0xa3, 0x3e, 0x42, 0xdb, 0xe4,
	0xbb, 0x3c, 0x24, 0x0e, 0x65, 0x64, 0x40, 0x7b, 0x1e, 0xa3, 0x0a, 0x88, 0xea, 0x0b, 0x1e, 0xf6,
	0xfa, 0x09, 0x44, 0x27, 0xc7, 0x64, 0x62, 0xa8, 0x0d, 0xe4, 0x3c, 0xb1, 0x10, 0x8f, 0xe9, 0x74,
	0x09, 0x22, 0xc3, 0x8e, 0xd4, 0x51, 0x30, 0x25, 0x89, 0x43, 0x7d, 0x5f, 0xda, 0xb9, 0xf0, 0xd8,
	0x1d, 0x39, 0x9d, 0x72, 0xde, 0x35, 0x27, 0x3e, 0xd5, 0x01, 0x65, 0x8e, 0xe3, 0x27, 0x6d, 0xed,
	0x26, 0xd8, 0x0f, 0xde, 0x8b, 0x0a, 0xe2, 0xc9, 0xa5, 0x05, 0xb1, 0x8d, 0x6e, 0x57, 0x6f, 0xe5,
	0x17, 0x44, 0x0e, 0xbd, 0x17, 0x66, 0x7a, 0x19, 0x2f, 0xa6, 0x33, 0x9d, 0xca, 0xee, 0xcf, 0x8a,
	0x68, 0x69, 0x62, 0x2a, 0xe3, 0x1b, 0xe3, 0x0c, 0xe6, 0xad, 0xf4, 0xea, 0xcd, 0x0b, 0xe5, 0x71,
	0x8e, 0x7f, 0x6d, 0x9d, 0x37, 0x3f, 0x4d, 0x35, 0xd8, 0x6a, 0x04, 0x4b, 0xb7, 0x57, 0xbc, 0x08,
	0x74, 0x8a, 0x19, 0x9c, 0x26, 0xc7, 0x0f, 0xbe, 0xa3, 0x69, 0xd9, 0xc1, 0xc7, 0xe6, 0xed, 0xd7,
	0x24, 0xcf, 0x31, 0xb8, 0x69, 0x56, 0x6a, 0x68, 0xbb, 0x7a, 0x3b, 0x9f, 0x95, 0x5c, 0x97, 0x3a,
	0x6b, 0x68, 0x75, 0xc4, 0xcb, 0x15, 0x34, 0x7b, 0x2a, 0x3c, 0x05, 0x86, 0x98, 0xd5, 0x5d, 0x6b,
	0x6b, 0xe3, 0x22, 0x6e, 0x7e, 0x54, 0x44, 0x4b, 0x13, 0x83, 0x37, 0xcd, 0x4d, 0xde, 0x44, 0xae,
	0x5e, 0xb3, 0xa3, 0x6f, 0x16, 0x76, 0xf2, 0xcd, 0xc2, 0xbe, 0x17, 0x0c, 0xd4, 0x70, 0xe3, 0x73,
	0xeb, 0xbc, 0xf9, 0x93, 0x34, 0x25, 0x91, 0x76, 0x9a, 0x92, 0x7a, 0x74, 0x24, 0x53, 0x67, 0xe4,
	0xd4, 0x53, 0x7d, 0xd3, 0x1c, 0xba, 0x82, 0xba, 0x1e, 0xf8, 0xae, 0x4c, 0x4d, 0x95, 0x37, 0x34,
	0x5b, 0x77, 0xf1, 0xcd, 0x31, 0x5b, 0xa1, 0x31, 0x31, 0xc5, 0xd6, 0xc5, 0xc1, 0x5f, 0xdf, 0xb5,
	0xb6, 0xaa, 0x97, 0x8e, 0x00, 0xfc, 0x77, 0x0b, 0x2d, 0x4d, 0xac, 0x81, 0x34, 0x0d, 0x79, 0xfb,
	0xe1, 0x42, 0x1a, 0x7e, 0x6e, 0x9d, 0x37, 0x87, 0x29, 0x16, 0x22, 0xe5, 0x34, 0x0b, 0x37, 0x8e,
	0x41, 0x04, 0x94, 0x01, 0x53, 0xfe, 0x90, 0xb8, 0xd3, 0xe2, 0xbc, 0x98, 0x23, 0xd0, 0x97, 0x8e,
	0xb9, 0xba, 0x75, 0x69, 0xc0, 0xd5, 0xd2, 0x8b, 0x62, 0x61, 0xef, 0xf7, 0xb3, 0xe7, 0xcd, 0x5f,
	0xcc, 0xa2, 0x52, 0xc3, 0xae, 0xe3, 0xa3, 0xd1, 0xc3, 0xa6, 0x24, 0xcd, 0xe3, 0x23, 0xdc, 0x38,
	0x16, 0xfc, 0xc4, 0x73, 0x41, 0x92, 0xfd, 0xd6, 0xbb, 0x07, 0x84, 0x0f, 0x40, 0x44, 0x5f, 0xae,
	0x08, 0x67, 0xe9, 0xb1, 0x20, 0x47, 0x13, 0xd9, 0x6e, 0xcc, 0xee, 0xd8, 0x75, 0xbb, 0xbe, 0x51,
	0xaa, 0x9d, 0xec, 0x6c, 0x59, 0xc5, 0xc6, 0x0a, 0xd5, 0x69, 0x74, 0x8c, 0x5a, 0xed, 0x43, 0xc9,
	0xd9, 0x6e, 0xe6, 0xa4, 0x75, 0xac, 0x47, 0xfd, 0x9b, 0xf8, 0x08, 0xdd, 0xcf, 0x8e, 0xfa, 0x50,
	0x82, 0x20, 0x2e, 0x87, 0x68, 0xd0, 0xf7, 0xe9, 0x09, 0x90, 0x01, 0x88, 0xc0, 0x93, 0xd2, 0xd3,
	0x3e, 0x70, 0xed, 0x02, 0x48, 0x39, 0xb1, 0x16, 0xec, 0xd6, 0x21, 0x2a, 0xbd, 0x55, 0xaf, 0xe3,
	0x6f, 0xa1, 0xb7, 0x27, 0x2d, 0x52, 0x46, 0x42, 0x06, 0x67, 0x83, 0x68, 0x9d, 0x81, 0x10, 0x5c,
	0x10, 0xee, 0x38, 0xa1, 0x00, 0x37, 0x09, 0x49, 0x82, 0x38, 0x01, 0x41, 0xa4, 0xe7, 0x82, 0xdd,
	0x6a, 0x6b, 0xcf, 0xea, 0xf8, 0x7d, 0xf4, 0x5e, 0xde, 0x12, 0x8a, 0x26, 0x5a, 0x87, 0xbb, 0x43,
	0xbd, 0x88, 0x02, 0xea, 0x77, 0xb9, 0x08, 0xa8, 0xd2, 0xa6, 0x79, 0xca, 0xe9, 0x80, 0x2a, 0xa7,
	0x6f, 0x54, 0x46, 0x37, 0xc7, 0xba, 0x76, 0xeb, 0xa1, 0xbe, 0x60, 0x07, 0xdf, 0x43, 0xfb, 0x17,
	0x5f, 0x30, 0x32, 0x34, 0x31, 0x91, 0x35, 0x31, 0x5f, 0x93, 0x7a, 0x70, 0xb8, 0xfa, 0x6d, 0x8c,
	0xfa, 0xd2, 0xfe, 0xe0, 0x6f, 0x16, 0xfa, 0xab, 0x35, 0xaa, 0x87, 0x3f, 0x5a, 0xe5, 0x12, 0xfe,
	0xd8, 0x6a, 0xc6, 0x04, 0xf1, 0x6c, 0xb6, 0xa4, 0xf6, 0x5b, 0x3f, 0x51, 0x0b, 0xcf, 0xb8, 0xa5,
	0x31, 0xa1, 0xea, 0x6b, 0x7b, 0x8e, 0x69, 0x30, 0x7d, 0x89, 0xb4, 0xc9, 0x33, 0x9d, 0xea, 0xb1,
	0x40, 0x33, 0x3f, 0x10, 0xdc, 0x98, 0xed, 0x72, 0xdf, 0xe7, 0xa7, 0x91, 0x4b, 0xfa, 0x5a, 0x2e,
	0xbc, 0xef, 0x47, 0x88, 0x7d, 0xee, 0x02, 0xe9, 0xfa, 0xfc, 0xd4, 0xde, 0x9c, 0x69, 0x94, 0x4d,
	0x31, 0x86, 0xaa, 0xbf, 0x3b, 0x6f, 0xbe, 0x59, 0xf2, 0xe7, 0xc0, 0xf6, 0x76, 0x51, 0x35, 0x9a,
	0xdd, 0x18, 0xdf, 0x17, 0x34, 0x72, 0x8c, 0xba, 0x71, 0x46, 0xd1, 0x6b, 0x71, 0x39, 0xe3, 0xb5,
	0x58, 0x68, 0x7e, 0xc5, 0xd2, 0x77, 0xac, 0xe3, 0xc2, 0x07, 0xa3, 0xcf, 0xb1, 0x3f, 0xb4, 0x0a,
	0x2f, 0xac, 0xc2, 0x27, 0x56, 0xe1, 0x73, 0xab, 0xf0, 0x07, 0xab, 0xf0, 0x4f, 0xab, 0xf0, 0xdb,
	0x62, 0xa1, 0x33, 0x67, 0xba, 0xf2, 0xcd, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0xc0, 0x18, 0x8e,
	0x73, 0xd8, 0x15, 0x00, 0x00,
}
