// Code generated by protoc-gen-go. DO NOT EDIT.
// source: command-line-arguments/all.proto

package accounts

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"
import _ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
import types "github.com/openbank/gunk/gunk/v1/types"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// MajorType describes the type of the account.
type MajorType int32

const (
	MajorType__ MajorType = 0
	// MajorType_Checking account.
	MajorType_Checking MajorType = 1
	// MajorType_Saving account.
	MajorType_Saving MajorType = 2
	// MajorType_TimeDeposit for a time deposit account.
	MajorType_TimeDeposit MajorType = 3
	// MajorType_CommercialLoan for a business loan account.
	MajorType_CommercialLoan MajorType = 4
	// MajorType_MortgageLoan for a home loan account.
	MajorType_MortgageLoan MajorType = 5
	// MajorType_ConsumerLoan for a consumer loan account.
	MajorType_ConsumerLoan MajorType = 6
)

var MajorType_name = map[int32]string{
	0: "_",
	1: "Checking",
	2: "Saving",
	3: "TimeDeposit",
	4: "CommercialLoan",
	5: "MortgageLoan",
	6: "ConsumerLoan",
}
var MajorType_value = map[string]int32{
	"_":              0,
	"Checking":       1,
	"Saving":         2,
	"TimeDeposit":    3,
	"CommercialLoan": 4,
	"MortgageLoan":   5,
	"ConsumerLoan":   6,
}

func (x MajorType) String() string {
	return proto.EnumName(MajorType_name, int32(x))
}
func (MajorType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_all_1cd3f353c050fb22, []int{0}
}

// MajorCategory describes the category of the account.
type MajorCategory int32

const (
	MajorCategory__ MajorCategory = 0
	// MajorCategory_Dep for deposit category.
	MajorCategory_Dep MajorCategory = 1
	// MajorCategory_Loan for loan category.
	MajorCategory_Loan MajorCategory = 2
)

var MajorCategory_name = map[int32]string{
	0: "_",
	1: "Dep",
	2: "Loan",
}
var MajorCategory_value = map[string]int32{
	"_":    0,
	"Dep":  1,
	"Loan": 2,
}

func (x MajorCategory) String() string {
	return proto.EnumName(MajorCategory_name, int32(x))
}
func (MajorCategory) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_all_1cd3f353c050fb22, []int{1}
}

// EntityType describes the type of the entity.
type EntityType int32

const (
	EntityType__ EntityType = 0
	// EntityType_Pers is an individual customer.
	EntityType_Pers EntityType = 1
	// EntityType_Org is an organisation customer.
	EntityType_Org EntityType = 2
)

var EntityType_name = map[int32]string{
	0: "_",
	1: "Pers",
	2: "Org",
}
var EntityType_value = map[string]int32{
	"_":    0,
	"Pers": 1,
	"Org":  2,
}

func (x EntityType) String() string {
	return proto.EnumName(EntityType_name, int32(x))
}
func (EntityType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_all_1cd3f353c050fb22, []int{2}
}

// Account holds all details about a bank account.
type Account struct {
	// AccountID is the unique identifier of an account.
	AccountID string `protobuf:"bytes,1,opt,name=AccountID,json=account_id,proto3" json:"AccountID,omitempty"`
	// Branch ...
	Branch string `protobuf:"bytes,2,opt,name=Branch,json=branch,proto3" json:"Branch,omitempty"`
	// BranchName ...
	BranchName string `protobuf:"bytes,3,opt,name=BranchName,json=branch_name,proto3" json:"BranchName,omitempty"`
	// Status is the status of the account.
	Status string `protobuf:"bytes,4,opt,name=Status,json=status,proto3" json:"Status,omitempty"`
	// AccruedInterestAtMaturityDate ...
	AccruedInterestAtMaturityDate string `protobuf:"bytes,5,opt,name=AccruedInterestAtMaturityDate,json=accrued_interest_at_maturity_date,proto3" json:"AccruedInterestAtMaturityDate,omitempty"`
	// AmountDue ...
	AmountDue *types.Amount `protobuf:"bytes,6,opt,name=AmountDue,json=amount_due,proto3" json:"AmountDue,omitempty"`
	// AvailableBalance ...
	AvailableBalance *types.Amount `protobuf:"bytes,7,opt,name=AvailableBalance,json=available_balance,proto3" json:"AvailableBalance,omitempty"`
	// AvailableCreditLimit ...
	AvailableCreditLimit string `protobuf:"bytes,8,opt,name=AvailableCreditLimit,json=available_credit_limit,proto3" json:"AvailableCreditLimit,omitempty"`
	// CheckingInterestRate ...
	CheckingInterestRate string `protobuf:"bytes,9,opt,name=CheckingInterestRate,json=checking_interest_rate,proto3" json:"CheckingInterestRate,omitempty"`
	// ContractDate is the date of the contract initialization.
	ContractDate string `protobuf:"bytes,10,opt,name=ContractDate,json=contract_date,proto3" json:"ContractDate,omitempty"`
	// CreditLimit is the allowed credit limit.
	CreditLimit string `protobuf:"bytes,11,opt,name=CreditLimit,json=credit_limit,proto3" json:"CreditLimit,omitempty"`
	// CurrentAccruedInterest ...
	CurrentAccruedInterest string `protobuf:"bytes,12,opt,name=CurrentAccruedInterest,json=current_accrued_interest,proto3" json:"CurrentAccruedInterest,omitempty"`
	// CurrentBalance ...
	CurrentBalance *types.Amount `protobuf:"bytes,13,opt,name=CurrentBalance,json=current_balance,proto3" json:"CurrentBalance,omitempty"`
	// CurrentTerm is the account validity period.
	CurrentTerm string `protobuf:"bytes,14,opt,name=CurrentTerm,json=current_term,proto3" json:"CurrentTerm,omitempty"`
	// DueDate is the loan maturity date.
	DueDate string `protobuf:"bytes,15,opt,name=DueDate,json=due_date,proto3" json:"DueDate,omitempty"`
	// InterestRate ...
	InterestRate string `protobuf:"bytes,16,opt,name=InterestRate,json=interest_rate,proto3" json:"InterestRate,omitempty"`
	// MajorType is the account type.
	MajorType MajorType `protobuf:"varint,17,opt,name=MajorType,json=major_type,proto3,enum=accounts.MajorType" json:"MajorType,omitempty"`
	// MajorCategory is the account category.
	MajorCategory MajorCategory `protobuf:"varint,18,opt,name=MajorCategory,json=major_category,proto3,enum=accounts.MajorCategory" json:"MajorCategory,omitempty"`
	// MaturityDate is the maturity date, format is ISO 8601
	MaturityDate string `protobuf:"bytes,19,opt,name=MaturityDate,json=maturity_date,proto3" json:"MaturityDate,omitempty"`
	// NextPaymentDueDate ...
	NextPaymentDueDate string `protobuf:"bytes,20,opt,name=NextPaymentDueDate,json=next_payment_due_date,proto3" json:"NextPaymentDueDate,omitempty"`
	// OwnerName is the name of the account's owner.
	OwnerName string `protobuf:"bytes,21,opt,name=OwnerName,json=owner_name,proto3" json:"OwnerName,omitempty"`
	// StartDate ...
	StartDate            string   `protobuf:"bytes,22,opt,name=StartDate,json=start_date,proto3" json:"StartDate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_all_1cd3f353c050fb22, []int{0}
}
func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (dst *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(dst, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetAccountID() string {
	if m != nil {
		return m.AccountID
	}
	return ""
}

func (m *Account) GetBranch() string {
	if m != nil {
		return m.Branch
	}
	return ""
}

func (m *Account) GetBranchName() string {
	if m != nil {
		return m.BranchName
	}
	return ""
}

func (m *Account) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Account) GetAccruedInterestAtMaturityDate() string {
	if m != nil {
		return m.AccruedInterestAtMaturityDate
	}
	return ""
}

func (m *Account) GetAmountDue() *types.Amount {
	if m != nil {
		return m.AmountDue
	}
	return nil
}

func (m *Account) GetAvailableBalance() *types.Amount {
	if m != nil {
		return m.AvailableBalance
	}
	return nil
}

func (m *Account) GetAvailableCreditLimit() string {
	if m != nil {
		return m.AvailableCreditLimit
	}
	return ""
}

func (m *Account) GetCheckingInterestRate() string {
	if m != nil {
		return m.CheckingInterestRate
	}
	return ""
}

func (m *Account) GetContractDate() string {
	if m != nil {
		return m.ContractDate
	}
	return ""
}

func (m *Account) GetCreditLimit() string {
	if m != nil {
		return m.CreditLimit
	}
	return ""
}

func (m *Account) GetCurrentAccruedInterest() string {
	if m != nil {
		return m.CurrentAccruedInterest
	}
	return ""
}

func (m *Account) GetCurrentBalance() *types.Amount {
	if m != nil {
		return m.CurrentBalance
	}
	return nil
}

func (m *Account) GetCurrentTerm() string {
	if m != nil {
		return m.CurrentTerm
	}
	return ""
}

func (m *Account) GetDueDate() string {
	if m != nil {
		return m.DueDate
	}
	return ""
}

func (m *Account) GetInterestRate() string {
	if m != nil {
		return m.InterestRate
	}
	return ""
}

func (m *Account) GetMajorType() MajorType {
	if m != nil {
		return m.MajorType
	}
	return MajorType__
}

func (m *Account) GetMajorCategory() MajorCategory {
	if m != nil {
		return m.MajorCategory
	}
	return MajorCategory__
}

func (m *Account) GetMaturityDate() string {
	if m != nil {
		return m.MaturityDate
	}
	return ""
}

func (m *Account) GetNextPaymentDueDate() string {
	if m != nil {
		return m.NextPaymentDueDate
	}
	return ""
}

func (m *Account) GetOwnerName() string {
	if m != nil {
		return m.OwnerName
	}
	return ""
}

func (m *Account) GetStartDate() string {
	if m != nil {
		return m.StartDate
	}
	return ""
}

// GetAccountRequest is the request envelope to get an account by its identifier.
type GetAccountRequest struct {
	AccountID            string   `protobuf:"bytes,1,opt,name=AccountID,json=account_id,proto3" json:"AccountID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountRequest) Reset()         { *m = GetAccountRequest{} }
func (m *GetAccountRequest) String() string { return proto.CompactTextString(m) }
func (*GetAccountRequest) ProtoMessage()    {}
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_all_1cd3f353c050fb22, []int{1}
}
func (m *GetAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountRequest.Unmarshal(m, b)
}
func (m *GetAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountRequest.Marshal(b, m, deterministic)
}
func (dst *GetAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountRequest.Merge(dst, src)
}
func (m *GetAccountRequest) XXX_Size() int {
	return xxx_messageInfo_GetAccountRequest.Size(m)
}
func (m *GetAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountRequest proto.InternalMessageInfo

func (m *GetAccountRequest) GetAccountID() string {
	if m != nil {
		return m.AccountID
	}
	return ""
}

// GetAccountsRequest is the request envelope to get a list of filtered accounts.
type GetAccountsRequest struct {
	// NextStartingIndex is a cursor for pagination. It's an AccountID that defines
	// the current place in the total list of Accounts.
	NextStartingIndex    string   `protobuf:"bytes,1,opt,name=NextStartingIndex,json=next_starting_index,proto3" json:"NextStartingIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountsRequest) Reset()         { *m = GetAccountsRequest{} }
func (m *GetAccountsRequest) String() string { return proto.CompactTextString(m) }
func (*GetAccountsRequest) ProtoMessage()    {}
func (*GetAccountsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_all_1cd3f353c050fb22, []int{2}
}
func (m *GetAccountsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountsRequest.Unmarshal(m, b)
}
func (m *GetAccountsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountsRequest.Marshal(b, m, deterministic)
}
func (dst *GetAccountsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountsRequest.Merge(dst, src)
}
func (m *GetAccountsRequest) XXX_Size() int {
	return xxx_messageInfo_GetAccountsRequest.Size(m)
}
func (m *GetAccountsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountsRequest proto.InternalMessageInfo

func (m *GetAccountsRequest) GetNextStartingIndex() string {
	if m != nil {
		return m.NextStartingIndex
	}
	return ""
}

// GetAccountsResponse wraps the list of accounts.
type GetAccountsResponse struct {
	// Result is a list containing up to 20 Accounts.
	Result []*Account `protobuf:"bytes,1,rep,name=Result,json=result,proto3" json:"Result,omitempty"`
	// HasMore indicates if there are more accounts available.
	HasMore              bool     `protobuf:"varint,2,opt,name=HasMore,json=has_more,proto3" json:"HasMore,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountsResponse) Reset()         { *m = GetAccountsResponse{} }
func (m *GetAccountsResponse) String() string { return proto.CompactTextString(m) }
func (*GetAccountsResponse) ProtoMessage()    {}
func (*GetAccountsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_all_1cd3f353c050fb22, []int{3}
}
func (m *GetAccountsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountsResponse.Unmarshal(m, b)
}
func (m *GetAccountsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountsResponse.Marshal(b, m, deterministic)
}
func (dst *GetAccountsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountsResponse.Merge(dst, src)
}
func (m *GetAccountsResponse) XXX_Size() int {
	return xxx_messageInfo_GetAccountsResponse.Size(m)
}
func (m *GetAccountsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountsResponse proto.InternalMessageInfo

func (m *GetAccountsResponse) GetResult() []*Account {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *GetAccountsResponse) GetHasMore() bool {
	if m != nil {
		return m.HasMore
	}
	return false
}

// AccountRole ...
type AccountRole struct {
	// EntityNumber ...
	EntityNumber string `protobuf:"bytes,1,opt,name=EntityNumber,json=entity_number,proto3" json:"EntityNumber,omitempty"`
	// EntityType ...
	EntityType EntityType `protobuf:"varint,2,opt,name=EntityType,json=entity_type,proto3,enum=accounts.EntityType" json:"EntityType,omitempty"`
	// Role ...
	Role                 string   `protobuf:"bytes,3,opt,name=Role,json=role,proto3" json:"Role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountRole) Reset()         { *m = AccountRole{} }
func (m *AccountRole) String() string { return proto.CompactTextString(m) }
func (*AccountRole) ProtoMessage()    {}
func (*AccountRole) Descriptor() ([]byte, []int) {
	return fileDescriptor_all_1cd3f353c050fb22, []int{4}
}
func (m *AccountRole) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountRole.Unmarshal(m, b)
}
func (m *AccountRole) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountRole.Marshal(b, m, deterministic)
}
func (dst *AccountRole) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountRole.Merge(dst, src)
}
func (m *AccountRole) XXX_Size() int {
	return xxx_messageInfo_AccountRole.Size(m)
}
func (m *AccountRole) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountRole.DiscardUnknown(m)
}

var xxx_messageInfo_AccountRole proto.InternalMessageInfo

func (m *AccountRole) GetEntityNumber() string {
	if m != nil {
		return m.EntityNumber
	}
	return ""
}

func (m *AccountRole) GetEntityType() EntityType {
	if m != nil {
		return m.EntityType
	}
	return EntityType__
}

func (m *AccountRole) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

// DebitTransaction ...
type DebitTransaction struct {
	// Amount ...
	Amount string `protobuf:"bytes,1,opt,name=Amount,json=amount,proto3" json:"Amount,omitempty"`
	// DebitAccount ...
	DebitAccount string `protobuf:"bytes,2,opt,name=DebitAccount,json=debit_account,proto3" json:"DebitAccount,omitempty"`
	// ExchangeRate ...
	ExchangeRate string `protobuf:"bytes,3,opt,name=ExchangeRate,json=exchange_rate,proto3" json:"ExchangeRate,omitempty"`
	// IsFx ...
	IsFx                 bool     `protobuf:"varint,4,opt,name=IsFx,json=is_fx,proto3" json:"IsFx,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DebitTransaction) Reset()         { *m = DebitTransaction{} }
func (m *DebitTransaction) String() string { return proto.CompactTextString(m) }
func (*DebitTransaction) ProtoMessage()    {}
func (*DebitTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_all_1cd3f353c050fb22, []int{5}
}
func (m *DebitTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DebitTransaction.Unmarshal(m, b)
}
func (m *DebitTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DebitTransaction.Marshal(b, m, deterministic)
}
func (dst *DebitTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DebitTransaction.Merge(dst, src)
}
func (m *DebitTransaction) XXX_Size() int {
	return xxx_messageInfo_DebitTransaction.Size(m)
}
func (m *DebitTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_DebitTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_DebitTransaction proto.InternalMessageInfo

func (m *DebitTransaction) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *DebitTransaction) GetDebitAccount() string {
	if m != nil {
		return m.DebitAccount
	}
	return ""
}

func (m *DebitTransaction) GetExchangeRate() string {
	if m != nil {
		return m.ExchangeRate
	}
	return ""
}

func (m *DebitTransaction) GetIsFx() bool {
	if m != nil {
		return m.IsFx
	}
	return false
}

// CreateAccountRequest wraps all required fields for an account creation.
type CreateAccountRequest struct {
	// AccountID is the identifier of the account.
	AccountID string `protobuf:"bytes,1,opt,name=AccountID,json=account_id,proto3" json:"AccountID,omitempty"`
	// Description ...
	Description string `protobuf:"bytes,2,opt,name=Description,json=description,proto3" json:"Description,omitempty"`
	// AccountRoles ...
	AccountRoles []*AccountRole `protobuf:"bytes,3,rep,name=AccountRoles,json=account_roles,proto3" json:"AccountRoles,omitempty"`
	// Branch ...
	Branch string `protobuf:"bytes,4,opt,name=Branch,json=branch,proto3" json:"Branch,omitempty"`
	// Customer ...
	Customer string `protobuf:"bytes,5,opt,name=Customer,json=customer,proto3" json:"Customer,omitempty"`
	// DebitTransaction ...
	DebitTransaction *DebitTransaction `protobuf:"bytes,6,opt,name=DebitTransaction,json=debit_transaction,proto3" json:"DebitTransaction,omitempty"`
	// InterestRate ...
	InterestRate string `protobuf:"bytes,7,opt,name=InterestRate,json=interest_rate,proto3" json:"InterestRate,omitempty"`
	// MajortType is the type of the account.
	MajorType MajorType `protobuf:"varint,8,opt,name=MajorType,json=major_type,proto3,enum=accounts.MajorType" json:"MajorType,omitempty"`
	// MaturityDate ...
	MaturityDate string `protobuf:"bytes,9,opt,name=MaturityDate,json=maturity_date,proto3" json:"MaturityDate,omitempty"`
	// Minor ...
	Minor                string   `protobuf:"bytes,10,opt,name=Minor,json=minor,proto3" json:"Minor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountRequest) Reset()         { *m = CreateAccountRequest{} }
func (m *CreateAccountRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAccountRequest) ProtoMessage()    {}
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_all_1cd3f353c050fb22, []int{6}
}
func (m *CreateAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountRequest.Unmarshal(m, b)
}
func (m *CreateAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountRequest.Marshal(b, m, deterministic)
}
func (dst *CreateAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountRequest.Merge(dst, src)
}
func (m *CreateAccountRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAccountRequest.Size(m)
}
func (m *CreateAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountRequest proto.InternalMessageInfo

func (m *CreateAccountRequest) GetAccountID() string {
	if m != nil {
		return m.AccountID
	}
	return ""
}

func (m *CreateAccountRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateAccountRequest) GetAccountRoles() []*AccountRole {
	if m != nil {
		return m.AccountRoles
	}
	return nil
}

func (m *CreateAccountRequest) GetBranch() string {
	if m != nil {
		return m.Branch
	}
	return ""
}

func (m *CreateAccountRequest) GetCustomer() string {
	if m != nil {
		return m.Customer
	}
	return ""
}

func (m *CreateAccountRequest) GetDebitTransaction() *DebitTransaction {
	if m != nil {
		return m.DebitTransaction
	}
	return nil
}

func (m *CreateAccountRequest) GetInterestRate() string {
	if m != nil {
		return m.InterestRate
	}
	return ""
}

func (m *CreateAccountRequest) GetMajorType() MajorType {
	if m != nil {
		return m.MajorType
	}
	return MajorType__
}

func (m *CreateAccountRequest) GetMaturityDate() string {
	if m != nil {
		return m.MaturityDate
	}
	return ""
}

func (m *CreateAccountRequest) GetMinor() string {
	if m != nil {
		return m.Minor
	}
	return ""
}

// CreateAccountResponse is the response envelope for an account creation.
type CreateAccountResponse struct {
	// AccountID is the unique identifier of the newly created account.
	AccountID string `protobuf:"bytes,1,opt,name=AccountID,json=account_id,proto3" json:"AccountID,omitempty"`
	// CreditTransactionNumber is the transaction number of the credited account.
	CreditTransactionNumber string `protobuf:"bytes,2,opt,name=CreditTransactionNumber,json=credit_transaction_number,proto3" json:"CreditTransactionNumber,omitempty"`
	// DebitTransactionNumber is the transaction number of the debited account.
	DebitTransactionNumber string `protobuf:"bytes,3,opt,name=DebitTransactionNumber,json=debit_transaction_number,proto3" json:"DebitTransactionNumber,omitempty"`
	// MajorType is the type of the account.
	MajorType MajorType `protobuf:"varint,4,opt,name=MajorType,json=major_type,proto3,enum=accounts.MajorType" json:"MajorType,omitempty"`
	// Minor ...
	Minor                string   `protobuf:"bytes,5,opt,name=Minor,json=minor,proto3" json:"Minor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountResponse) Reset()         { *m = CreateAccountResponse{} }
func (m *CreateAccountResponse) String() string { return proto.CompactTextString(m) }
func (*CreateAccountResponse) ProtoMessage()    {}
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_all_1cd3f353c050fb22, []int{7}
}
func (m *CreateAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountResponse.Unmarshal(m, b)
}
func (m *CreateAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountResponse.Marshal(b, m, deterministic)
}
func (dst *CreateAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountResponse.Merge(dst, src)
}
func (m *CreateAccountResponse) XXX_Size() int {
	return xxx_messageInfo_CreateAccountResponse.Size(m)
}
func (m *CreateAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountResponse proto.InternalMessageInfo

func (m *CreateAccountResponse) GetAccountID() string {
	if m != nil {
		return m.AccountID
	}
	return ""
}

func (m *CreateAccountResponse) GetCreditTransactionNumber() string {
	if m != nil {
		return m.CreditTransactionNumber
	}
	return ""
}

func (m *CreateAccountResponse) GetDebitTransactionNumber() string {
	if m != nil {
		return m.DebitTransactionNumber
	}
	return ""
}

func (m *CreateAccountResponse) GetMajorType() MajorType {
	if m != nil {
		return m.MajorType
	}
	return MajorType__
}

func (m *CreateAccountResponse) GetMinor() string {
	if m != nil {
		return m.Minor
	}
	return ""
}

// UpdateAccountRequest wraps all fields available for update.
type UpdateAccountRequest struct {
	// AccountID is the unique identifier of the account to update.
	AccountID string `protobuf:"bytes,1,opt,name=AccountID,json=account_id,proto3" json:"AccountID,omitempty"`
	// Description ...
	Description          string   `protobuf:"bytes,2,opt,name=Description,json=description,proto3" json:"Description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateAccountRequest) Reset()         { *m = UpdateAccountRequest{} }
func (m *UpdateAccountRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateAccountRequest) ProtoMessage()    {}
func (*UpdateAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_all_1cd3f353c050fb22, []int{8}
}
func (m *UpdateAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateAccountRequest.Unmarshal(m, b)
}
func (m *UpdateAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateAccountRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateAccountRequest.Merge(dst, src)
}
func (m *UpdateAccountRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateAccountRequest.Size(m)
}
func (m *UpdateAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateAccountRequest proto.InternalMessageInfo

func (m *UpdateAccountRequest) GetAccountID() string {
	if m != nil {
		return m.AccountID
	}
	return ""
}

func (m *UpdateAccountRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

// DeleteAccountRequest is the request envelope to delete an account.
type DeleteAccountRequest struct {
	// AccountID is the unique identifier of the account to delete.
	AccountID            string   `protobuf:"bytes,1,opt,name=AccountID,json=account_id,proto3" json:"AccountID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAccountRequest) Reset()         { *m = DeleteAccountRequest{} }
func (m *DeleteAccountRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAccountRequest) ProtoMessage()    {}
func (*DeleteAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_all_1cd3f353c050fb22, []int{9}
}
func (m *DeleteAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAccountRequest.Unmarshal(m, b)
}
func (m *DeleteAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAccountRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAccountRequest.Merge(dst, src)
}
func (m *DeleteAccountRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAccountRequest.Size(m)
}
func (m *DeleteAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAccountRequest proto.InternalMessageInfo

func (m *DeleteAccountRequest) GetAccountID() string {
	if m != nil {
		return m.AccountID
	}
	return ""
}

func init() {
	proto.RegisterType((*Account)(nil), "accounts.Account")
	proto.RegisterType((*GetAccountRequest)(nil), "accounts.GetAccountRequest")
	proto.RegisterType((*GetAccountsRequest)(nil), "accounts.GetAccountsRequest")
	proto.RegisterType((*GetAccountsResponse)(nil), "accounts.GetAccountsResponse")
	proto.RegisterType((*AccountRole)(nil), "accounts.AccountRole")
	proto.RegisterType((*DebitTransaction)(nil), "accounts.DebitTransaction")
	proto.RegisterType((*CreateAccountRequest)(nil), "accounts.CreateAccountRequest")
	proto.RegisterType((*CreateAccountResponse)(nil), "accounts.CreateAccountResponse")
	proto.RegisterType((*UpdateAccountRequest)(nil), "accounts.UpdateAccountRequest")
	proto.RegisterType((*DeleteAccountRequest)(nil), "accounts.DeleteAccountRequest")
	proto.RegisterEnum("accounts.MajorType", MajorType_name, MajorType_value)
	proto.RegisterEnum("accounts.MajorCategory", MajorCategory_name, MajorCategory_value)
	proto.RegisterEnum("accounts.EntityType", EntityType_name, EntityType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountServiceClient is the client API for AccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountServiceClient interface {
	// GetAccount retrieves the detail of an account, selected by its id.
	GetAccount(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*Account, error)
	// GetAccounts returns a list containing up to 20 accounts.
	GetAccounts(ctx context.Context, in *GetAccountsRequest, opts ...grpc.CallOption) (*GetAccountsResponse, error)
	// CreateAccount creates a new account and return its id.
	CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountResponse, error)
	// UpdateAccount updates an account.
	UpdateAccount(ctx context.Context, in *UpdateAccountRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// DeleteAccount deletes an account.
	DeleteAccount(ctx context.Context, in *DeleteAccountRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type accountServiceClient struct {
	cc *grpc.ClientConn
}

func NewAccountServiceClient(cc *grpc.ClientConn) AccountServiceClient {
	return &accountServiceClient{cc}
}

func (c *accountServiceClient) GetAccount(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*Account, error) {
	out := new(Account)
	err := c.cc.Invoke(ctx, "/accounts.AccountService/GetAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) GetAccounts(ctx context.Context, in *GetAccountsRequest, opts ...grpc.CallOption) (*GetAccountsResponse, error) {
	out := new(GetAccountsResponse)
	err := c.cc.Invoke(ctx, "/accounts.AccountService/GetAccounts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountResponse, error) {
	out := new(CreateAccountResponse)
	err := c.cc.Invoke(ctx, "/accounts.AccountService/CreateAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) UpdateAccount(ctx context.Context, in *UpdateAccountRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/accounts.AccountService/UpdateAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) DeleteAccount(ctx context.Context, in *DeleteAccountRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/accounts.AccountService/DeleteAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServiceServer is the server API for AccountService service.
type AccountServiceServer interface {
	// GetAccount retrieves the detail of an account, selected by its id.
	GetAccount(context.Context, *GetAccountRequest) (*Account, error)
	// GetAccounts returns a list containing up to 20 accounts.
	GetAccounts(context.Context, *GetAccountsRequest) (*GetAccountsResponse, error)
	// CreateAccount creates a new account and return its id.
	CreateAccount(context.Context, *CreateAccountRequest) (*CreateAccountResponse, error)
	// UpdateAccount updates an account.
	UpdateAccount(context.Context, *UpdateAccountRequest) (*empty.Empty, error)
	// DeleteAccount deletes an account.
	DeleteAccount(context.Context, *DeleteAccountRequest) (*empty.Empty, error)
}

func RegisterAccountServiceServer(s *grpc.Server, srv AccountServiceServer) {
	s.RegisterService(&_AccountService_serviceDesc, srv)
}

func _AccountService_GetAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accounts.AccountService/GetAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetAccount(ctx, req.(*GetAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_GetAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).GetAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accounts.AccountService/GetAccounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).GetAccounts(ctx, req.(*GetAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accounts.AccountService/CreateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).CreateAccount(ctx, req.(*CreateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_UpdateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).UpdateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accounts.AccountService/UpdateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).UpdateAccount(ctx, req.(*UpdateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_DeleteAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).DeleteAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accounts.AccountService/DeleteAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).DeleteAccount(ctx, req.(*DeleteAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccountService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "accounts.AccountService",
	HandlerType: (*AccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAccount",
			Handler:    _AccountService_GetAccount_Handler,
		},
		{
			MethodName: "GetAccounts",
			Handler:    _AccountService_GetAccounts_Handler,
		},
		{
			MethodName: "CreateAccount",
			Handler:    _AccountService_CreateAccount_Handler,
		},
		{
			MethodName: "UpdateAccount",
			Handler:    _AccountService_UpdateAccount_Handler,
		},
		{
			MethodName: "DeleteAccount",
			Handler:    _AccountService_DeleteAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "command-line-arguments/all.proto",
}

func init() {
	proto.RegisterFile("command-line-arguments/all.proto", fileDescriptor_all_1cd3f353c050fb22)
}

var fileDescriptor_all_1cd3f353c050fb22 = []byte{
	// 1704 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x58, 0x41, 0x6c, 0xe3, 0x58,
	0x19, 0xb6, 0xd3, 0x34, 0x93, 0xbc, 0x24, 0xdd, 0xd4, 0xed, 0x74, 0x4d, 0x76, 0x67, 0xd6, 0x14,
	0x81, 0x66, 0xca, 0x34, 0x19, 0xba, 0x02, 0xc1, 0x08, 0x10, 0x69, 0xb2, 0x65, 0x07, 0x4d, 0x67,
	0xab, 0xb6, 0x48, 0xc0, 0xc5, 0x7a, 0x71, 0xfe, 0x3a, 0x66, 0xed, 0x67, 0xf3, 0xde, 0x73, 0xdb,
	0xb0, 0x42, 0x5a, 0x71, 0x1a, 0x6e, 0xab, 0xa2, 0xbd, 0x72, 0xe2, 0xb2, 0x37, 0x8e, 0x88, 0x1b,
	0x07, 0xee, 0x2b, 0x71, 0xd9, 0x2b, 0x12, 0x77, 0xae, 0x1c, 0xd1, 0x7b, 0x7e, 0x8e, 0xed, 0xd8,
	0x55, 0x19, 0x90, 0xf6, 0x32, 0xd3, 0xfc, 0xff, 0xf7, 0xff, 0xfe, 0xfe, 0xef, 0xfd, 0xef, 0xff,
	0x9d, 0x20, 0xcb, 0x09, 0x83, 0x00, 0x93, 0xd9, 0xbe, 0xef, 0x11, 0xd8, 0xc7, 0xd4, 0x8d, 0x03,
	0x20, 0x9c, 0x0d, 0xb1, 0xef, 0x0f, 0x22, 0x1a, 0xf2, 0xd0, 0x68, 0x62, 0xc7, 0x09, 0x63, 0xc2,
	0x59, 0xff, 0x6d, 0x37, 0x0c, 0x5d, 0x1f, 0x86, 0x38, 0xf2, 0x86, 0x98, 0x90, 0x90, 0x63, 0xee,
	0x85, 0x84, 0x25, 0xb8, 0xfe, 0x13, 0xf9, 0x9f, 0xb3, 0xef, 0x02, 0xd9, 0x67, 0x57, 0xd8, 0x75,
	0x81, 0x0e, 0xc3, 0x48, 0x22, 0x2a, 0xd0, 0x6f, 0xa9, 0x5c, 0xf2, 0xd3, 0x34, 0xbe, 0x18, 0x42,
	0x10, 0xf1, 0x85, 0x72, 0x3e, 0x75, 0x3d, 0x3e, 0x8f, 0xa7, 0x03, 0x27, 0x0c, 0x86, 0x61, 0x04,
	0x64, 0x8a, 0xc9, 0x87, 0x43, 0x37, 0x4e, 0xff, 0xb9, 0xfc, 0xd6, 0x90, 0x2f, 0x22, 0xc8, 0x91,
	0xdc, 0xfd, 0xbc, 0x85, 0xee, 0x8d, 0x12, 0x9e, 0xc6, 0x63, 0xd4, 0x52, 0x7f, 0x3e, 0x9f, 0x98,
	0xba, 0xa5, 0x3f, 0x6a, 0x1d, 0xa2, 0xa6, 0x66, 0x6a, 0x8f, 0xb4, 0xa7, 0xda, 0x89, 0x76, 0x8a,
	0x54, 0x3d, 0xb6, 0x37, 0x33, 0x76, 0x51, 0xe3, 0x90, 0x62, 0xe2, 0xcc, 0xcd, 0x5a, 0x09, 0xd7,
	0x98, 0x4a, 0x8f, 0xf1, 0x4d, 0x84, 0x12, 0xcc, 0x4b, 0x1c, 0x80, 0xb9, 0x56, 0xc2, 0xb5, 0x13,
	0x9c, 0x4d, 0x70, 0x00, 0x22, 0xe1, 0x19, 0xc7, 0x3c, 0x66, 0x66, 0xbd, 0x9c, 0x90, 0x49, 0x8f,
	0x71, 0x8e, 0x1e, 0x8c, 0x1c, 0x87, 0xc6, 0x30, 0x7b, 0x4e, 0x38, 0x50, 0x60, 0x7c, 0xc4, 0x8f,
	0x31, 0x8f, 0xa9, 0xc7, 0x17, 0x13, 0xcc, 0xc1, 0x5c, 0x2f, 0x85, 0x7e, 0x15, 0x27, 0x01, 0xb6,
	0xa7, 0x22, 0x6c, 0xcc, 0xed, 0x40, 0xc5, 0xd8, 0x33, 0xcc, 0xc1, 0xf8, 0x2e, 0x6a, 0x8d, 0x02,
	0x51, 0xd7, 0x24, 0x06, 0xb3, 0x61, 0xe9, 0x8f, 0xda, 0x07, 0xdd, 0x81, 0x94, 0x69, 0x90, 0xd8,
	0x57, 0x44, 0x90, 0x36, 0x7b, 0x16, 0x83, 0x71, 0x84, 0x7a, 0xa3, 0x4b, 0xec, 0xf9, 0x78, 0xea,
	0xc3, 0x21, 0xf6, 0x31, 0x71, 0xc0, 0xbc, 0x77, 0x57, 0x82, 0x4d, 0x9c, 0x86, 0xd8, 0xd3, 0x24,
	0xc6, 0xf8, 0x11, 0xda, 0x5e, 0xe6, 0x19, 0x53, 0x98, 0x79, 0xfc, 0x85, 0x17, 0x78, 0xdc, 0x6c,
	0x96, 0xca, 0xd9, 0xc9, 0x82, 0x1d, 0x09, 0xb4, 0x7d, 0x81, 0x14, 0x19, 0xc6, 0x73, 0x70, 0x3e,
	0xf4, 0x88, 0x9b, 0x4a, 0x73, 0x2a, 0x04, 0x69, 0x95, 0x33, 0x38, 0x0a, 0x97, 0x29, 0x42, 0x85,
	0x0a, 0x43, 0xd4, 0x19, 0x87, 0x84, 0x53, 0xec, 0x70, 0x29, 0x25, 0x2a, 0x45, 0x76, 0x1d, 0xe5,
	0x4f, 0x64, 0xdb, 0x47, 0xed, 0x3c, 0xd7, 0x76, 0x09, 0xdf, 0x29, 0x30, 0x9c, 0xa0, 0x9d, 0x71,
	0x4c, 0x29, 0x10, 0xbe, 0x72, 0x84, 0x66, 0xa7, 0x14, 0x69, 0x3a, 0x09, 0xd2, 0x5e, 0x3d, 0x3c,
	0xe3, 0x10, 0x6d, 0xa8, 0x2c, 0xa9, 0xde, 0xdd, 0xbb, 0xf4, 0x7e, 0x23, 0x4d, 0x96, 0xaa, 0x2d,
	0x88, 0x27, 0xa6, 0x73, 0xa0, 0x81, 0xb9, 0x51, 0x41, 0x5c, 0x45, 0x70, 0xa0, 0x81, 0xf1, 0x75,
	0x74, 0x6f, 0x12, 0x83, 0xd4, 0xe4, 0x8d, 0x12, 0xb4, 0x39, 0x8b, 0x21, 0x91, 0x63, 0x88, 0x3a,
	0x05, 0xe5, 0x7b, 0x65, 0xfd, 0x8a, 0x82, 0xff, 0x10, 0xb5, 0x8e, 0xf1, 0x2f, 0x43, 0x7a, 0xbe,
	0x88, 0xc0, 0xdc, 0xb4, 0xf4, 0x47, 0x1b, 0x07, 0x5b, 0x83, 0x74, 0x62, 0x0c, 0x96, 0xae, 0x62,
	0xf3, 0x05, 0xc2, 0x6c, 0x8b, 0x5a, 0x8d, 0x9f, 0xa0, 0xae, 0x04, 0x8d, 0x31, 0x07, 0x37, 0xa4,
	0x0b, 0xd3, 0x90, 0x39, 0xde, 0x5c, 0xc9, 0x91, 0xba, 0x0b, 0x79, 0x36, 0x92, 0x3c, 0x8e, 0xf2,
	0x09, 0xf2, 0x85, 0x7b, 0xb4, 0x55, 0x26, 0x5f, 0xbc, 0x33, 0x3f, 0x40, 0xc6, 0x4b, 0xb8, 0xe6,
	0x27, 0x78, 0x21, 0x86, 0x5e, 0xaa, 0xcf, 0x76, 0x29, 0xec, 0x3e, 0x81, 0x6b, 0x6e, 0x47, 0x09,
	0xcc, 0x5e, 0x8a, 0xf5, 0x18, 0xb5, 0x3e, 0xb8, 0x22, 0x40, 0xe5, 0x60, 0xb8, 0x5f, 0x1e, 0x34,
	0xa1, 0x70, 0x26, 0x73, 0xe1, 0x31, 0x6a, 0x9d, 0x71, 0x4c, 0x93, 0xa6, 0xdc, 0x29, 0x43, 0x99,
	0x70, 0xca, 0xac, 0xcf, 0x1a, 0x4d, 0xad, 0xa7, 0x99, 0xda, 0xee, 0x11, 0xda, 0xfc, 0x31, 0x70,
	0x35, 0xc9, 0x4e, 0xe1, 0x57, 0xb1, 0xe8, 0x9c, 0xff, 0x7e, 0xb6, 0x2d, 0xf3, 0xfc, 0x0c, 0x19,
	0x59, 0x1e, 0x96, 0x26, 0x7a, 0x86, 0x36, 0x45, 0xe9, 0x92, 0x94, 0xbc, 0x6e, 0x33, 0xb8, 0xae,
	0x48, 0xb8, 0x25, 0x2b, 0x67, 0x0a, 0x65, 0x7b, 0x02, 0xb6, 0xcc, 0xfc, 0x11, 0xda, 0x2a, 0x64,
	0x66, 0x51, 0x48, 0x18, 0x18, 0xdf, 0x46, 0x8d, 0x53, 0x60, 0xb1, 0xcf, 0x4d, 0xdd, 0x5a, 0x7b,
	0xd4, 0x3e, 0xd8, 0xcc, 0xce, 0x52, 0x61, 0x8b, 0x63, 0x91, 0x4a, 0xb0, 0xe8, 0xd0, 0xf7, 0x31,
	0x3b, 0x0e, 0x29, 0xc8, 0x61, 0xdc, 0x2c, 0x76, 0xe8, 0x1c, 0x33, 0x3b, 0x08, 0x69, 0x26, 0xcf,
	0x67, 0x3a, 0x6a, 0xa7, 0xe2, 0x84, 0xbe, 0xec, 0xdc, 0xf7, 0x08, 0xf7, 0xf8, 0xe2, 0x65, 0x1c,
	0x4c, 0x81, 0x56, 0xd4, 0xd2, 0x05, 0xe9, 0xb7, 0x89, 0x04, 0x18, 0x23, 0x84, 0x92, 0x00, 0xd9,
	0xba, 0x35, 0xd9, 0x76, 0xdb, 0x19, 0xd5, 0xcc, 0x57, 0x9c, 0xf6, 0x2a, 0x89, 0x6c, 0xde, 0x87,
	0xa8, 0x2e, 0x9e, 0x5d, 0xb1, 0x14, 0xea, 0x34, 0xf4, 0x33, 0xae, 0x7f, 0xd5, 0x51, 0x6f, 0x02,
	0x53, 0x8f, 0x9f, 0x53, 0x4c, 0x18, 0x76, 0xc4, 0x22, 0x14, 0xab, 0x22, 0xb9, 0xe7, 0x15, 0x54,
	0x1b, 0xc9, 0x78, 0x16, 0x45, 0xc9, 0x38, 0x55, 0x68, 0xc5, 0x96, 0xea, 0xce, 0x84, 0xdf, 0x56,
	0xb4, 0xa5, 0x0a, 0xd7, 0xce, 0x1c, 0x13, 0x17, 0xe4, 0xfd, 0x5d, 0xab, 0x50, 0x41, 0xf9, 0x93,
	0xfb, 0xfb, 0x0e, 0xaa, 0x3f, 0x67, 0x47, 0xd7, 0x72, 0x5d, 0x15, 0x25, 0x5f, 0xf7, 0x98, 0x7d,
	0x91, 0x1d, 0xf6, 0x1f, 0xeb, 0x68, 0x7b, 0x4c, 0x01, 0x73, 0xf8, 0x9f, 0x5b, 0xd2, 0x78, 0x82,
	0xda, 0x13, 0x60, 0x0e, 0xf5, 0xe4, 0x6b, 0x41, 0x45, 0x35, 0xed, 0x59, 0xe6, 0x36, 0x8e, 0x50,
	0x27, 0x77, 0xc0, 0xcc, 0x5c, 0x93, 0xdd, 0x74, 0xbf, 0xd4, 0x4d, 0xc2, 0x5b, 0x2c, 0x31, 0x7d,
	0xa4, 0x38, 0x04, 0x96, 0x5b, 0xf2, 0xf5, 0x5b, 0x97, 0xfc, 0x37, 0x50, 0x73, 0x1c, 0x33, 0x1e,
	0x06, 0x40, 0x2b, 0xd6, 0x6f, 0xd3, 0x51, 0x3e, 0xe3, 0xac, 0x7c, 0x90, 0x6a, 0xd9, 0xf6, 0x33,
	0x5e, 0xab, 0x88, 0xe2, 0xe2, 0x4c, 0x0e, 0x8c, 0xe7, 0x3a, 0x61, 0x75, 0xe8, 0xde, 0x7b, 0xad,
	0xa1, 0xdb, 0x7c, 0xfd, 0xa1, 0xbb, 0x3a, 0x28, 0x5b, 0x77, 0x0d, 0x4a, 0x0b, 0xad, 0x1f, 0x7b,
	0x24, 0xa4, 0x15, 0xfb, 0x74, 0x3d, 0x10, 0x8e, 0x65, 0x9b, 0xfc, 0xa5, 0x86, 0xee, 0xaf, 0xb4,
	0x89, 0x1a, 0x0b, 0xaf, 0xd1, 0x27, 0x47, 0xe8, 0xcd, 0x64, 0x29, 0xe7, 0x44, 0x54, 0xd7, 0xba,
	0xdc, 0x33, 0x5f, 0x51, 0x0b, 0x3a, 0xa7, 0x68, 0x7a, 0xc5, 0x27, 0x68, 0x67, 0xf5, 0x2c, 0x54,
	0x9a, 0xf2, 0xbd, 0x30, 0x4b, 0xe7, 0x92, 0x66, 0x29, 0xa8, 0x5d, 0x7f, 0x7d, 0xb5, 0x97, 0xe2,
	0xad, 0xdf, 0x25, 0xde, 0x15, 0xda, 0xfe, 0x69, 0x34, 0xfb, 0xf2, 0xae, 0xd8, 0xf2, 0xc1, 0xcf,
	0xd1, 0xf6, 0x04, 0x7c, 0xf8, 0x3f, 0x1e, 0x9c, 0xa6, 0xda, 0xfb, 0x54, 0xcf, 0xc9, 0x65, 0xb4,
	0x90, 0x6e, 0xf7, 0xb4, 0x7e, 0xad, 0xa9, 0x19, 0x3d, 0xd4, 0x4c, 0x5f, 0xee, 0x7a, 0xba, 0xb4,
	0x6c, 0xa0, 0xc6, 0x19, 0xbe, 0x14, 0x9f, 0x6b, 0xf2, 0xf3, 0x16, 0x6a, 0x9f, 0x7b, 0x01, 0x4c,
	0x20, 0x0a, 0x99, 0xc7, 0x7b, 0x6b, 0xd2, 0xb8, 0x83, 0x36, 0xc6, 0x61, 0x10, 0x00, 0x75, 0x3c,
	0xec, 0xbf, 0x08, 0x31, 0xe9, 0xd5, 0xa5, 0x7d, 0x1b, 0x75, 0x8e, 0x43, 0xca, 0x5d, 0xec, 0x82,
	0xb4, 0xae, 0xa7, 0xd6, 0x71, 0x48, 0x58, 0x1c, 0x00, 0x95, 0xd6, 0x86, 0xb0, 0xf6, 0x6b, 0xa6,
	0xb6, 0xf7, 0xbd, 0x95, 0x17, 0x8d, 0x3c, 0xb5, 0x36, 0x5a, 0x9b, 0x40, 0xa4, 0x58, 0x75, 0x50,
	0x5d, 0x86, 0xd6, 0x96, 0xa1, 0xdf, 0xc9, 0x6f, 0x8a, 0x7c, 0x5c, 0x07, 0xd5, 0x4f, 0x80, 0x32,
	0x15, 0xd8, 0x46, 0x6b, 0x1f, 0x50, 0x37, 0x8b, 0x3b, 0xf8, 0x5d, 0x0b, 0x6d, 0x28, 0xf9, 0xce,
	0x80, 0x5e, 0x7a, 0x0e, 0x18, 0x5f, 0xe8, 0x08, 0x65, 0x3b, 0xd3, 0x78, 0x2b, 0xeb, 0xa3, 0xd2,
	0xae, 0xef, 0x97, 0xf7, 0xe6, 0xee, 0xa7, 0xfa, 0xcd, 0xc8, 0xcf, 0xbe, 0xe9, 0x6c, 0x9d, 0x02,
	0xa7, 0x1e, 0x5c, 0x82, 0x85, 0x89, 0xa5, 0xc0, 0xfd, 0x17, 0xa9, 0x91, 0x59, 0xd8, 0xf7, 0xad,
	0x19, 0xe6, 0xd8, 0xba, 0xa0, 0x61, 0x90, 0xc3, 0x3c, 0xb1, 0x18, 0xf8, 0xe0, 0x70, 0x98, 0x59,
	0xd3, 0x85, 0xc5, 0xe7, 0x60, 0x65, 0x07, 0x69, 0x2d, 0xc2, 0xd8, 0x62, 0x71, 0x14, 0xf9, 0x1e,
	0xcc, 0x06, 0xbf, 0xfd, 0xfb, 0x3f, 0x7f, 0x5f, 0xeb, 0x1b, 0xa6, 0xf8, 0xce, 0x95, 0xb2, 0x19,
	0x7e, 0xb4, 0xec, 0x89, 0xdf, 0xbc, 0xaa, 0x69, 0x9f, 0xd4, 0x64, 0x3b, 0x18, 0xff, 0xaa, 0xa1,
	0x76, 0xee, 0x75, 0xc0, 0x78, 0xbb, 0xaa, 0xb6, 0xf4, 0xfd, 0xa3, 0xff, 0xe0, 0x16, 0x6f, 0x32,
	0x2c, 0x76, 0xff, 0x50, 0xbb, 0x19, 0x7d, 0x5c, 0xcb, 0x2a, 0xdd, 0x7c, 0xe1, 0x31, 0x2e, 0xeb,
	0x59, 0x7e, 0x1b, 0xfd, 0x87, 0x7e, 0x0a, 0x3c, 0xa6, 0x84, 0x59, 0xd8, 0xf2, 0x85, 0x57, 0xbc,
	0xd8, 0x63, 0x8f, 0x78, 0xc4, 0xb5, 0xe2, 0xc8, 0xe2, 0xa1, 0x75, 0xf0, 0x74, 0x89, 0x1e, 0x58,
	0x3f, 0x0f, 0x63, 0xcb, 0xc1, 0xc4, 0x8a, 0xb0, 0xeb, 0x11, 0xcc, 0xc1, 0xe2, 0x73, 0x1a, 0xc6,
	0xee, 0x3c, 0x85, 0x08, 0x25, 0x64, 0xd9, 0x0b, 0x91, 0xa0, 0xe2, 0xb5, 0xc7, 0xf2, 0x88, 0xd0,
	0x86, 0x5a, 0x2c, 0x9e, 0x32, 0x51, 0x05, 0xe1, 0xcc, 0x72, 0xb0, 0xef, 0xb3, 0x41, 0x25, 0x5c,
	0xd1, 0x61, 0xab, 0xfa, 0x86, 0x17, 0xd2, 0xe2, 0x63, 0x51, 0x50, 0xc9, 0xac, 0x5e, 0xda, 0x05,
	0x4d, 0x48, 0xd4, 0xdf, 0x30, 0x3a, 0x79, 0xf5, 0x73, 0x8a, 0x7f, 0xa6, 0xa3, 0x6e, 0x61, 0xd6,
	0x1a, 0x0f, 0x33, 0x55, 0xab, 0x76, 0x75, 0xff, 0x9d, 0x5b, 0xfd, 0x4a, 0xf7, 0xb3, 0x9b, 0xd1,
	0xbb, 0x39, 0xd5, 0x13, 0x50, 0xbe, 0xbb, 0xd4, 0x70, 0x17, 0xa2, 0x13, 0xb8, 0x4a, 0xcd, 0x92,
	0xe8, 0xe6, 0x33, 0x7d, 0x6f, 0xf7, 0x36, 0xae, 0x7f, 0xd3, 0x51, 0xb7, 0x30, 0xdb, 0xf2, 0x5c,
	0xab, 0x86, 0x5e, 0x7f, 0x67, 0x90, 0xfc, 0x44, 0x30, 0x48, 0x7f, 0x22, 0x18, 0xbc, 0x17, 0x44,
	0x7c, 0xb1, 0xfb, 0xeb, 0x9b, 0xd1, 0xcb, 0x1c, 0xc5, 0x24, 0x36, 0x4f, 0xf1, 0x69, 0x62, 0x62,
	0x39, 0x9b, 0x75, 0xe5, 0xf1, 0xb9, 0x6c, 0x1f, 0xa1, 0xf1, 0x85, 0x07, 0xfe, 0x8c, 0xad, 0x34,
	0xf9, 0x83, 0x67, 0xfa, 0x5e, 0xff, 0xce, 0x3e, 0x37, 0xfe, 0xa4, 0xa3, 0x6e, 0x61, 0x54, 0xe6,
	0xeb, 0xa8, 0x9a, 0xa1, 0xb7, 0xd6, 0x01, 0x37, 0xa3, 0xef, 0xe7, 0xea, 0x48, 0x62, 0xf3, 0x75,
	0x3c, 0x3c, 0x01, 0x1a, 0x60, 0x02, 0x84, 0xfb, 0x0b, 0x6b, 0xb6, 0xea, 0x56, 0x57, 0x73, 0xef,
	0x4e, 0xca, 0xfd, 0xb5, 0x57, 0x35, 0xed, 0xf0, 0x6b, 0xef, 0xeb, 0x27, 0xda, 0x2f, 0x96, 0xbf,
	0xe5, 0x7c, 0xac, 0x6b, 0xaf, 0x74, 0xed, 0x13, 0x5d, 0xfb, 0xb3, 0xae, 0x7d, 0xa1, 0x6b, 0xff,
	0xd6, 0xb5, 0xcf, 0x6b, 0xda, 0xb4, 0x21, 0x29, 0xbe, 0xfb, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x79, 0x23, 0x9d, 0x1a, 0x15, 0x12, 0x00, 0x00,
}
